### ISSUE TITLE
LiteDB collections become corrupted

### ISSUE THREAD

**Issue by tabtile** [litedb-org/LiteDB#1041]
Dear mbdavid,

I use v4.11 in a secure mode - single threaded, encrypted with exclusive access.
However, after a certain volume of usage, certain collections of the database become corrupted and selecting records from them raises the following exception:

```
Excpetion=System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at LiteDB.IndexService.<FindAll>d__13.MoveNext()
   at LiteDB.LinqExtensions.<>c__DisplayClass2_0`2.<<DistinctBy>g___0>d.MoveNext()
   at LiteDB.QueryCursor.Fetch(TransactionService trans, DataService data, BsonReader bsonReader)
   at LiteDB.LiteEngine.<Find>d__9.MoveNext()
   at LiteDB.LiteEngine.<Find>d__13.MoveNext()
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

When I try to open the database in LiteDB viewer and click on the corrupted collection, I get this error:

```
LiteDB.LiteException: Datafile is not a LiteDB database.
   **at LiteDB.HeaderPage.ReadContent(ByteReader reader)
   at LiteDB.BasePage.ReadPage(Byte[] buffer)
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.QueryCursor.Fetch(TransactionService trans, DataService data, BsonReader bsonReader)
   at LiteDB.LiteEngine.<Find>d__9.MoveNext()
   at LiteDB.LiteEngine.<Find>d__13.MoveNext()
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()**
   at LiteDBViewer.MainForm.FillDataGridView(IEnumerable`1 documents)
   at LiteDBViewer.MainForm.listBox_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

I would be happy for your assistance, thank you!!

**Comment by mbdavid** [comment]
Hi @tabtile, sorry about that. I get some issues about data consistency last days and I will investigate this weekend. So, can you tell about your environment so I will have a start point. 

- Is Windows 10? Are you using .NET full or .NET core? 
- You tell that you are using single thread. I presume that your application is WinForms (as stacktrace/namespace says). So, there is no concurrency? No 2 threads works in same datafile (using same LiteDatabase instance or in 2 distinct database instances)
- Are you using `LiteDatabase` inside a `using` statment? Like every command you do you open/execute/close? Or you have a single open LiteDatabase instance and execute all command over this instance (in this case, when you call .Dispose())

I think can be a bug/problem when save data into disk and but not all page are saved....  that is quite hard to detect.

Also, to recovery data, try use master branch version.... I wrote a code to read data-only and re-create datafile.

**Comment by tabtile** [comment]
Dear mbdavid,

Thank you for your kind and detailed email! 

Regarding your questions:
- I'm using Windows 10 running .NET full.
- I'm using a single thread, my app is a windows service (the winforms stack trace derives from litedb viewer app). Only one thread works on a data file at once using a continuously opened connection that is disposed and recreated only when there is an error in the query execution.
- I'm not using litedatabase in a using statement because I want to keep an open connection, and (as I've mentioned) I'm executing all my commands within the same instance (unless an exception is thrown, then I'm disposing and recreating the connection)
- my workflow is that I'm using collections with indexes and inserting entries to them over time. At some point I'm cleaning up old entries from the collection (which might affect the index structure) and then continue to insert to new entries to it... maybe it creates a problem with the indexes structure which corrupts the entire collection?)

**Just a thought following your direction- If I will create/dispose the connection for every query, will it persist the pages and solve the problem?**

Regarding compiling the master branch, is it stable in your opinion for operational use?

Thank you for your time and effort!

**Comment by tabtile** [comment]
BTW - your recovery method needs to accept a password for encrypted databases.

**Comment by tabtile** [comment]
I've debugged your master branch with my corrupted database, here is the exception:

![image](https://user-images.githubusercontent.com/34836541/43363731-d92c8d40-9313-11e8-97e1-e54a5342cf38.png)

**Comment by CSchmitt812** [comment]
I have the same problem like @tabtile. How we can recover the Database?

**Comment by fabiofinn** [comment]
i'm with the same problem... any solution?

**Comment by serkaneksi78** [comment]
I have the same problem. How we can recover the Database?

**Comment by RoiArthur** [comment]
Dear mbdavid ,

Gratulations first for this **lightweight useful and performant** library.
I regrettably encounter same issue

No way to protect that part of code ? May I help you ?

**Comment by nwestfall** [comment]
We started receiving this issue with larger LiteDB datasets.  I mean, quick larger I had to remove `Compact()` cause it would take 5+ minutes to finish.

**Comment by JKamsker** [comment]
The `KeyNotFoundException` in `IndexService.FindAll` and the viewer's "Datafile is not a LiteDB database" are two faces of the same v4 problem: an index or data pointer in the file points at the wrong page, so reads land on garbage. It was never pinned to a single v4 bug, and v4 is no longer maintained.

Since v5.0 the storage engine is different. Committed pages go to a `-log` file first and reach the data file only at checkpoint ([DiskService.cs](https://github.com/litedb-org/LiteDB/blob/47268cb4/LiteDB/Engine/Disk/DiskService.cs#L167)). Index walks validate page types and are loop-guarded ([IndexService.cs](https://github.com/litedb-org/LiteDB/blob/47268cb4/LiteDB/Engine/Services/IndexService.cs#L209)), and detected corruption raises `LiteException` 999. With `auto-rebuild=true` the file is rebuilt on the next open ([LiteEngine.cs](https://github.com/litedb-org/LiteDB/blob/47268cb4/LiteDB/Engine/LiteEngine.cs#L112)), and `db.Rebuild()` uses the password from the connection string, so encrypted files are covered too.

To salvage a v4 file, open a copy with `Password=…;Upgrade=true`. Please try the latest prerelease:

```
dotnet add package LiteDB --prerelease
```

If this doesn't cover your case, comment here and we'll reopen it.
