### ISSUE TITLE
v4.1.4 Datafile is not a LiteDB database.

### ISSUE THREAD

**Issue by jonginleee** [litedb-org/LiteDB#1046]
Dear mbdavid,

I'm digging these issues below. 
I can't still reproduce them, but many users keep reporting these issues to our error reporting system.
It is UWP project and uses 4.1.4 version. You may have some hints to solve them.

Thx.

**Message**

> Datafile is not a LiteDB database.

**Delete Collection**
>    at LiteDB.HeaderPage.ReadContent(ByteReader reader)
   at LiteDB.BasePage.ReadPage(Byte[] buffer)
   at T LiteDB.PageService.GetPage[T](UInt32) + 0x79
   at LiteDB.CollectionService.Get(String name)
   at LiteDB.LiteEngine.GetCollectionPage(String name, Boolean addIfNotExits)
   at LiteDB.LiteEngine.<GetIndexes>d__19.MoveNext()
   at Boolean System.Linq.Enumerable+WhereEnumerableIterator`1.MoveNext() + 0x68
   at LiteDB.LiteEngine.Shrink(String password, IDiskService tempDisk)
   at LiteDB.LiteDatabase.Shrink(String password)
   at Boolean DesignMe.LocalStorage.InitializeCollection[T](String) + 0x365

**Upsert**

>    at LiteDB.HeaderPage.ReadContent(ByteReader) + 0x1b0
   at LiteDB.BasePage.ReadPage(Byte[]) + 0x8a
   at LiteDB.PageService.GetPage[T](UInt32) + 0x79
   at LiteDB.CollectionService.Get(String) + 0x6c
   at LiteDB.LiteEngine.GetCollectionPage(String, Boolean) + 0x25
   at LiteDB.LiteEngine.Transaction[T](String, Boolean, Func`2) + 0xe3
   at LiteDB.LiteEngine.Upsert(String, IEnumerable`1, BsonType) + 0xa8
   at LiteDB.LiteCollection`1.Upsert(IEnumerable`1) + 0x46
   at DesignMe.LocalStorage.Upsert[T](List`1, String) + 0x461

**Find**

>    at LiteDB.HeaderPage.ReadContent(ByteReader) + 0x1b0
   at LiteDB.BasePage.ReadPage(Byte[]) + 0x8a
   at LiteDB.PageService.GetPage[T](UInt32) + 0x79
   at LiteDB.CollectionService.Get(String) + 0x6c
   at LiteDB.LiteEngine.GetCollectionPage(String, Boolean) + 0x25
   at LiteDB.LiteEngine.<Find>d__9.MoveNext() + 0x176
   at LiteDB.LiteEngine.<Find>d__13.MoveNext() + 0xf8
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext() + 0x144
   at LiteDB.LiteQueryable`1.<ToEnumerable>d__21.MoveNext() + 0xfa
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1) + 0x77
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1) + 0x122
   at DesignMe.LocalStorage.GetAll[T](String) + 0x5f
   at DesignMe.LocalStorageExtentions.LoadFromLocal(Dictionary`2) + 0x3a

**Comment by rcurtis** [comment]
I am currently dealing with this issue as well.  When a power loss occurs the db file often becomes corrupted.

**Comment by Pokis** [comment]
Facing this issue as well.
We are using encryption, no concurrency, about 50k rows (but inserting only one by one in small operations). We use only inserts. 
This happens when application using the DB crashes, it sometimes corrupts the DB.

**Comment by JKamsker** [comment]
In v4 this message means a page the engine read as the header didn't contain the LiteDB signature. The file was left inconsistent, and the follow-up comments tie it to power loss and app crashes during writes. v4 overwrote changed pages in place in the data file, so an interruption at the wrong moment could leave pointers to pages that were never fully written.

Since v5.0 there are no in-place writes during a transaction. Commits are appended to a `-log` file and flushed ([DiskService.cs](https://github.com/litedb-org/LiteDB/blob/47268cb4/LiteDB/Engine/Disk/DiskService.cs#L167)), then copied into the data file at checkpoint, so a crash leaves the last committed state intact. Corruption that is still detected (wrong page type, loops) raises `LiteException` 999, and `auto-rebuild=true` repairs the file on the next open ([LiteEngine.cs](https://github.com/litedb-org/LiteDB/blob/47268cb4/LiteDB/Engine/LiteEngine.cs#L112)).

Existing v4 files can be converted by opening them with `Upgrade=true` (keep a backup). Please try the latest prerelease:

```
dotnet add package LiteDB --prerelease
```

If this doesn't cover your case, comment here and we'll reopen it.
