### ISSUE TITLE
Concurrency on Linux platform

### ISSUE THREAD

**Issue by khamoyer** [litedb-org/LiteDB#1087]
There is a problem on .net core 2.0 on Linux system with concurrent file access in exclusive mode and Timeout set to default. Wait logic has wrong condition in IOExceptionExtension.cs, I have changed IsLocked() to simply compare HResult with 11 and then it works well.

**Comment by mbdavid** [comment]
Hi @khamoyer, I will take a look on this... because this extensions I get from somewhere.... and this can be changed to netcore.

**Comment by Jaben** [comment]
@khamoyer I'm seeing this same issue -- it's complaining about "processing cannot access the file" (this is in a docker container) and it's not retrying:

```System.IO.IOException: The process cannot access the file '/data/AppData/hostedapp-17/appinstance-25/Seq.App.YouTrack.db' because it is being used by another process.
   at LiteDB.IOExceptionExtensions.WaitIfLocked(IOException ex, Int32 timer)
   at LiteDB.FileHelper.TryExec(Action action, TimeSpan timeout)
   at LiteDB.StreamExtensions.TryLock(FileStream stream, Int64 position, Int64 length, TimeSpan timeout)
   at LiteDB.FileDiskService.Lock(LockState state, TimeSpan timeout)
   at LiteDB.LockService.LockShared()
   at LiteDB.LockService.Shared()
   at LiteDB.LiteEngine.<Find>d__9.MoveNext()
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()```

**Comment by petermicuch** [comment]
This also appears for me. LitghDB file that is copied during docker build to /app/myfile.db can be used without any issues (I use that as default if not DB file exists). But as soon as I use volume mounted folder /app/data and copy DB file there to get that file persisted, I get the same exception as Jaben. First I though this might be because file owner is wrong. So I set attributes of the file and folder in the volume match my default file /app/myfile.db. But the exception is still there. Is there any plan to provide fix for this issue?
