### ISSUE TITLE
System.NotSupportedException: 'BSON type not supported'

### ISSUE THREAD

**Issue by DmytroHnatiuk** [litedb-org/LiteDB#1096]
Hi everybody, I've just faced an issue with my LiteDb. After some period of work I found this error in my stackTrace (BSON type not supported). I attached link where you can get db file. It's crashing while I am trying to open 'matches' table.

System.NotSupportedException: 'BSON type not supported'.

   at LiteDB.BsonReader.ReadElement(ByteReader reader, String& name)
   at LiteDB.BsonReader.ReadDocument(ByteReader reader)
   at LiteDB.QueryCursor.Fetch(TransactionService trans, DataService data, BsonReader bsonReader)
   at LiteDB.LiteEngine.Find(String collection, Query query, Int32 skip, Int32 limit)+MoveNext()
   at LiteDB.LiteEngine.Find(String collection, Query query, String[] includes, Int32 skip, Int32 limit)+MoveNext()
   at LiteDB.LiteCollection`1.Find(Query query, Int32 skip, Int32 limit)+MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at RoboWin.BLL.Components.MatchComponent.Services.MatchService.GetAll() in C:\Users\Dim_mon\Desktop\RoboWin\server\RoboWin\RoboWin.BLL\Components\MatchComponent\Services\MatchService.cs:line 30
   at RoboWin.Server.Controllers.MatchesController.GetAll() in C:\Users\Dim_mon\Desktop\RoboWin\server\RoboWin\RoboWin.Server\Controllers\MatchesController.cs:line 35
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()

My db dump
https://drive.google.com/open?id=1X3K7AnM-Nzx2NH-cXykTeBRI63bCqgYk

**Comment by Szilard95** [comment]
Hi, I have a similar issue, but think I found the problem.

Looks like when serializing dictionaries, if the key string contains null bytes (returned by `ToString()` call on the key object), it gets serialized as-is, see [BsonMapper.Serialize.cs#L141](https://github.com/mbdavid/LiteDB/blob/f2bc99db156b2f91ba5f8a3984f501034faf27fa/LiteDB/Mapper/BsonMapper.Serialize.cs#L141).

Then, during reading BSON elements, exceptions occur because those null bytes, see [BsonReader.cs#L147](https://github.com/mbdavid/LiteDB/blob/f2bc99db156b2f91ba5f8a3984f501034faf27fa/LiteDB/Document/Bson/BsonReader.cs#L147). The BSON reader reads the null byte int the `type` variable, and null is not a valid type value. The previously read element becomes the key string up to the first null byte.

To solve this, I changed the above mentioned dictionary serialization line to the following:
```c#
o.RawValue[key.ToString().Replace("\0", string.Empty)] = this.Serialize(type, value, depth);
```

**Comment by PLASMAchicken** [comment]
This seems to have happened in one of my production environments, I suppose @Szilard95 fix is only to prevent it but not too did the DB after it has happened right?

**Comment by lbnascimento** [comment]
@PLASMAchicken Could you open a new issue describing your problem?

**Comment by loebi-ch** [comment]
Same problem here with newest LiteDB version 5.0.8

**Comment by lbnascimento** [comment]
@loebi-ch Could you open a new issue describing your problem? Please include your datafile too, if possible.

**Comment by loebi-ch** [comment]
@lbnascimento I write you here, because I think it's not reasonable to open a new issue since the title of the issue describes exactly my problem and the issue is still marked as "Open".

After restarting my application, I cannot read the Collection "Computer" anymore. It gives me the error "BSON type not supported".

Here is my corrupted [LiteDB file](http://www.slyweb.ch/files/letec-deploy.db).

I'm using newest LiteDB version 5.0.8.

**Comment by GitOffice** [comment]
@loebi-ch  I have the same problem.

**Comment by johannes-fetz** [comment]
Same problem with version 5.0.8

**Comment by leandromolina** [comment]
I have the same problem, There is still no solution for this problem?

**Comment by PLASMAchicken** [comment]
This problem happened in my case, because I used LiteDB in an external thread, as Unity and possibly nor LiteDB are Threadsafe this caused some corruption.

The data then had random \0 and copies of itself in it.

**Comment by JKamsker** [comment]
The cause identified in this thread was a null character (`\0`) inside a dictionary key. Older versions wrote it unescaped into the BSON field name, so on read the name ended early and the next byte was taken as the type, hence "BSON type not supported". Since 5.0.9 the engine rejects such keys at write time with `Invalid null character (\0) was found in the string` ([BufferWriter.NetCore.cs](https://github.com/litedb-org/LiteDB/blob/47268cb4/LiteDB/Engine/Disk/Serializer/BufferWriter.NetCore.cs#L15)), so the file is never damaged in the first place.

Files that are already damaged can usually be repaired with `db.Rebuild()` or LiteDB Studio's Rebuild, as one comment confirmed. The same message can also come from other kinds of corruption, such as unsafe threading in the host app, which is what one Unity user traced theirs to.

Please try the latest prerelease:

```
dotnet add package LiteDB --prerelease
```

If you see this on a file created with a current version, a new issue with the data file and how the database is accessed would help.

Making this kind of damage raise the corruption error (so `auto-rebuild=true` repairs it automatically) is tracked in #2794. If this doesn't cover your case, comment here and we'll reopen it.
