### ISSUE TITLE
Concurrency Issue when using LiteDb inside Parallel.ForEach

### ISSUE THREAD

**Issue by mshenoy83** [litedb-org/LiteDB#1154]
This is more of an information than a bug report. 

I'm using LiteDb for importing data into an Azure database. Since importing uses a lot of DTU's I'm using LiteDb as a cache. I pull data from all the related tables and push them into LiteDb, add indexes and then create Bulk inserts/updates by querying LiteDb.

It worked great for a couple of times (probably because the initial tests had less data) but then I started facing concurrency issues. Specifically this error

```
System.AggregateException: One or more errors occurred. (Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at LiteDB.CacheService.GetPage(UInt32 pageID)
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.CollectionService.Get(String name)
   at LiteDB.LiteEngine.GetCollectionPage(String name, Boolean addIfNotExits)
   at LiteDB.LiteEngine.Find(String collection, Query query, Int32 skip, Int32 limit)+MoveNext()
   at LiteDB.LiteEngine.Find(String collection, Query query, String[] includes, Int32 skip, Int32 limit)+MoveNext()
   at LiteDB.LiteCollection`1.Find(Query query, Int32 skip, Int32 limit)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at LLGDataFeed.Components.XmlParser.<>c__DisplayClass39_6.<ParseXmlFiles>b__29(TextTab textTab) in C:\Development\GitRepos\****\LLGDataFeed\LLGDataFeed\Components\XmlParser.cs:line 491
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at LLGDataFeed.Components.XmlParser.ParseXmlFiles() in C:\Development\GitRepos\****\LLGDataFeed\LLGDataFeed\Components\XmlParser.cs:line 462
   at LLGDataFeed.App.Run() in C:\Development\GitRepos\****\LLGDataFeed\LLGDataFeed\App.cs:line 86
```
I googled for quite sometime added a question in StackOverflow but found nothing. Then in one of my searches I found [this](https://github.com/dotnet/corefx/issues/31186) which pushed me in the direction of the Concurrent Dictionary. So I forked LiteDb and made a change in the CacheService. I changed both Dictionaries to ConcurrentDictionaries created a local build and that seemed to solve the problem.

Not sure if @mbdavid  has already fixed this in the new version. But I thought I'll mention this anyway

**Comment by AliNazar1991** [comment]
Im facing this issue as well, is this planned to be fixed in upcoming versions?

**Comment by mbdavid** [comment]
Hi guys, this was complete re-write in v5. Can you test your code using current master branch version?

**Comment by AliNazar1991** [comment]
@mbdavid i have tested to create my database using the v5 alpha version, but im getting LiteDB.LiteException:"Document size exceed 2037500 limit", i have not seen this exception in the 4.1.4 version of LiteDB, and i have built my database several times with the 4.1.4 version. how can i overcome this size limitation? if i can get over this issue i can test the concurrency problem..

**Comment by mbdavid** [comment]
Hi @AliNazar1991, v5 implement a storage layer with a limit of 250 data pages for 1 single document (250 * 8149 bytes per page) =~ 2Mb each document (after serialize with BSON). If you need bigger documents you will need use FileStorage to store this document as file

**Comment by AliNazar1991** [comment]
@mbdavid this is sadly a huge blocker for me..

**Comment by JKamsker** [comment]
This is the same problem as #1416, which is fixed on the `dev` branch. `dev` ships as the LiteDB 6.x prereleases.

Please try the latest prerelease (currently **6.0.0-prerelease.81**):

```
dotnet add package LiteDB --prerelease
```

If the problem still happens on the prerelease, comment here with the version you used and a repro, and we'll reopen the issue.
