### ISSUE TITLE
FindAll() has null as the last object, when document seems correct

### ISSUE THREAD

**Issue by edwingr** [litedb-org/LiteDB#1181]
I'm consistently getting a System.NullReferenceException thrown when I run this code:

```
using (var db=new LiteDatabase(Properties.Settings.Default.@DbName))
{
      var a = db.GetCollection<Couple>(Properties.Resources.CouplesTable).FindAll().Last();
}
```

StackTrace:
 ```
   at LiteDB.BsonMapper.<>c__DisplayClass44_0.<RegisterDbRefItem>b__1(BsonValue bson, BsonMapper m)
   at LiteDB.BsonMapper.DeserializeObject(Type type, Object obj, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.ToObject(Type type, BsonDocument doc)
   at LiteDB.BsonMapper.ToObject[T](BsonDocument doc)
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at Tracker.Entities.EntityRelationships.GetCouples() in C:\Users\Edwin\source\repos\Tracker\Tracker\Entities\EntityRelationships.cs:line 35   

```
I've looked at the db with litedbmanager and the document is there, doesn't seem to have any problems

Relevant files here (including db):

[Exception.zip](https://github.com/mbdavid/LiteDB/files/2871555/Exception.zip)

**Comment by JKamsker** [comment]
The NullReferenceException comes from the v4 DbRef deserializer, which read `bson.AsDocument["$id"]` without checking that the stored value was a document. If a `DbRef` property holds `null` or a plain value, for example data written before the property became a reference, `AsDocument` is null and it throws. So the document looks fine in a viewer, but mapping it to `Couple` fails.

v5 checks for this and returns `null` for such values ([BsonMapper.cs](https://github.com/litedb-org/LiteDB/blob/47268cb4/LiteDB/Client/Mapper/BsonMapper.cs#L280)). Your attached database opens with the current version using `Upgrade=true`, and its reference fields (`Husband`, `Wife`, `Address`, …) are well-formed.

Please try the latest prerelease:

```
dotnet add package LiteDB --prerelease
```

If it still fails on the current version, please attach your mapper configuration and the referenced classes (`Individual`, `Address`, `Meeting`, …). If this doesn't cover your case, comment here and we'll reopen it.
