### ISSUE TITLE
Inconsistent behavior with possibly corrupt data file

### ISSUE THREAD

**Issue by omfgicbf** [litedb-org/LiteDB#1245]
I have a data file which is possibly corrupt and is causing issues when certain commands are used.

In the main calling application, the application throws:-
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> LiteDB.LiteException: Timeout. Database is locked for more than
00:01:00.
  at LiteDB.LockService.Read () [0x0006b] in <0e7fe05a592849968cfe23dfc2a26585>:0
  at LiteDB.LiteEngine+<Find>d__9.MoveNext () [0x000a7] in <0e7fe05a592849968cfe23dfc2a26585>:0
  at LiteDB.LiteEngine+<Find>d__13.MoveNext () [0x001e4] in <0e7fe05a592849968cfe23dfc2a26585>:0
  at LiteDB.LiteCollection`1+<Find>d__17[T].MoveNext () [0x000ba] in <0e7fe05a592849968cfe23dfc2a26585>:0
  at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00041] in <e7730c8b584547118b212a24053f001c>:0
  at LiteDB.LiteCollection`1[T].FindById (LiteDB.BsonValue id) [0x00033] in <0e7fe05a592849968cfe23dfc2a26585>:0
```

When I try to open the file in LiteDB.Shell, I can only see the data (which is all there) if I *don't* do a `show collections` first:-

```
# mono LiteDB.Shell.exe
Welcome to LiteDB Shell

Getting started with `help`, `help full` or `help <command>`

> open /opt/data/data.litedb
> show collections
objects
> db.objects.find
Your datafile did not terminate properly during the writing process. Reopen the file
> close
> open /opt/data/data.litedb
> show collections
objects
> db.objects.find
Your datafile did not terminate properly during the writing process. Reopen the file
> close
> open /opt/data/neon/data.litedb
> db.objects.find
[1]: {"_id": [ALL DATA HERE]
```

I tried opening the file using LiteDbExplorer, and it throws:-
```
LiteDB.LiteException: Your datafile did not terminate properly during the writing process. Reopen the file
   at LiteDB.LockService.DetectDatabaseChanges()
   at LiteDB.LockService.Read()
   at LiteDB.LiteEngine.<Find>d__9.MoveNext()
   at LiteDB.LiteEngine.<Find>d__13.MoveNext()
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
```

Is there a way to ensure the correct exception is thrown? e.g. "Your datafile did not terminate properly during the writing process"

I am unable to have my application take appropriate corrective action unless I know what the problem is.

Also, is there a way to detect what sort of corruption has happened? This seems to be related to an index or header, as the data is all there and accessible.

And, if this corruption is detectable, is it repairable?

I am opening this particular file with the default connection string (i.e. only supplying file path)

I am using LiteDB 4.1.4 on .NET 4.6.2. Using Mono on Linux and native on Windows.

**Comment by JensSchadron** [comment]
@omfgicbf Just a quick question, have you tried reading/upgrading the (possibly corrupted) database using v5?

**Comment by omfgicbf** [comment]
@JensSchadron I have tried v5 on at least one of the (different types of) corrupted databases I have, and it does seem to work. However, your question would probably be more appropriate on #1048 or #851, as the point I'm making above is about being able to accurately identify when corruption occurs, not how to recover from it afterwards (although that is also a core issue)

**Comment by omfgicbf** [comment]
Further to this, I've used the `LiteEngine.Recovery` method (as at commit f392bbb) and this seems to recover the file, however, there is are no reported errors. All I get is:-

```
Document recovery count: 904
```

It seems whatever the type of corruption, it is trivial and recoverable, however, at this point not detectable, which is a still a problem.

This means instead of running a "verify" method when I first open my database, I have to either wait for an exception somewhere in the data access code, or assume that the database is corrupted and recover (and then have to rename/move) every time I start my program.

There seems to be some confusion around these errors, as they are similar to ones that were reportedly caused by concurrency issues in v3, and in some cases before a fix introduced in v4.1.2.

I've found #641, #879, #992, #994, #1115, #1135, #1193 and #1194 where this issue is raised, on versions on or after v4.1.2, which means either the concurrency issue is not resolved, or more likely, this is not the cause in these cases and there is a real issue with database consistency after compromised writes.

**Comment by omfgicbf** [comment]
I've tracked down at least where the issue is occurring, though not why.

In my case, I have a corrupt file that has a collection page with an index (_id) that has an invalid `FreeIndexPageID` value; it is one more than the last page in the file (in this case `FreeIndexPageID` is 153 where the last page in the file is 152).

As this page ID is more than the number of pages, `FileDiskService.ReadPage` reads past the end of the file and returns an empty array.

`BasePage.ReadPage` returns an `EmptyPage` because the `pageType` byte is zero, and `PageService.GetPage` tries to cast this to an `IndexPage` (which is what it's expecting) and fails with the `InvalidCastException`.

What's not clear yet is why journaling is not working properly and why an interrupted write (during an `Insert`) is causing this invalid `FreeIndexPageId` value.

**Comment by mbdavid** [comment]
Hi @omfgicbf, this error was the reason to me rewrite all v5 storage engine, using now WAL. When I release v4, I tried to fix this same problem in v3... and no one can reproduce to me this error. I tried lots to fix and I believe can be concurrency, big operations (with disk persist during execution) or cache managment. And I review all this sources but don't where is the problem. I will talk with @JensSchadron about some ideas that I have to fix this in v4...

**Comment by omfgicbf** [comment]
Hi @mbdavid, thanks for the update.

In my case at least, I don't believe this is a concurrency issue. I have a single thread responsible for pulling items from a BlockingCollection and writing them to the database.

I've been trying to work out how the order of writing to disk might cause the issue I've seen (a collection page with indexes that point to incorrect page id's), perhaps this might be a clue to where the problem is? (i.e. updating the collection page first but a failure occurs before the other pages are moved?). I'm still trying to work out how all that works.

What I have noticed is the following in `TransactionService.PersistDirtyPages` (assuming journalling is enabled):-

1) write the journal
    1a) write all pages at end of file
    1b) flush
2) set header recovery flag true
3) write dirty pages (header page first)
4) set header recovery flag false, write the header page
5) flush

Given that flushing the cache does not guarantee the order in which blocks are written to the underlying device, a power-fail during these steps:-

- during (1) no issue(?); extra pages exist at the end of the file, but the last page marker has not been updated(?).
- during (2) as with (1); the header is not written until after (3) starts.
- during (3) an issue; we've overwritten some pages, but despite the fact we wrote the header page first, we don't know for sure it went to disk.
- during (4) an issue; because we haven't flushed yet, even if this write succeeds, we don't know all the blocks in (3) went to disk.
- after (5) we're all good... flush confirmed that blocks went to disk.

If we added `Flush` calls in between 2, 3 and 4, this might help preserve consistency, as a call to `FileStream.Flush(true)` would block until the data had been confirmed written to disk by the OS (NOTE: the normal caveats about device-based cache still apply)

**Comment by samcov** [comment]
I asked about this on twitter because I've tried many single file NoSql DB's in the past, and EVERY single one of them claiming to be thread safe, suffered from corruption problems.

I too had them all on on BlockingCollections in a producer/consumer pattern to ensure threading issues weren't a problem, but no luck, they still get corrupt.

I was hoping that LiteDB would be better, and hopefully it may, but having to wonder if your DB is corrupt is not a prescription for a solid product for customers.

I wish you guys good luck!

**Comment by JensSchadron** [comment]
Went over the entire issue list and in addition to the issues that @omfgicbf already listed, I've also found #801 #1000 #1083 and if we include older versions as well then these issues might be related as well #272 #449 #464 #470 #639

**Comment by dmariogatto** [comment]
I've been doing some troubleshooting around what causes the DB to get into this inconsistent state. I found something odd, which I hope will be helpful.

In Xamarin if I spin up multiple threads and have them all access the DB at the same time (reads & writes) then corruption is almost immediate (InvalidCastExceptions). However, the exact same code in a .NET Core console app and the database remains consistent, although it runs really slow. Sample [here](https://github.com/dmariogatto/litedb-concurrency).

**Comment by johannes-fetz** [comment]
@dmariogatto I have thousands of mobile devices running my application under Xamarin, but only Android is affected according to my console and not iOS

**Comment by JKamsker** [comment]
Your three questions, answered for the current version:

1. **Correct exception:** the v4 lock and journal code behind the timeout and "did not terminate properly" messages is gone. Structural corruption (wrong page type, looping chains) throws `LiteException` with `ErrorCode` 999 ([DataPage.cs](https://github.com/litedb-org/LiteDB/blob/47268cb4/LiteDB/Engine/Pages/DataPage.cs#L17)), so your application can react to it.
2. **Detection:** the engine marks the file invalid when that happens. There's no separate verify API; checksums are tracked in #1229. One gap: damage inside a document's own bytes still surfaces as `NotSupportedException: BSON type not supported`. That gap is tracked in #2794, which is why I'm closing this one as a duplicate of it.
3. **Repair:** with `auto-rebuild=true` the next open rebuilds the file, keeping a `-backup` copy and writing unreadable items to `_rebuild_errors` ([LiteEngine.cs](https://github.com/litedb-org/LiteDB/blob/47268cb4/LiteDB/Engine/LiteEngine.cs#L112)). `db.Rebuild()` does this on demand.

The window you traced, in-place page writes during commit, no longer exists. Since v5.0, commits are appended and flushed to a `-log` file ([DiskService.cs](https://github.com/litedb-org/LiteDB/blob/47268cb4/LiteDB/Engine/Disk/DiskService.cs#L167)) and copied in at checkpoint. v4 files convert with `Upgrade=true`.

Please try the latest prerelease:

```
dotnet add package LiteDB --prerelease
```

If this doesn't cover your case, comment here and we'll reopen it.
