### ISSUE TITLE
NullReferenceException on newly created collection

### ISSUE THREAD

**Issue by sekulicb** [litedb-org/LiteDB#1315]
Hi. I noticed that when you call GetCollection method for some entity, and if that collection does not exist, it should create a new one.  However if you call Count() down the line to check are there any elements at all, LiteDb throws NullReferenceException. This is the part of stack trace:

   at LiteDB.StreamExtensions.<>c__DisplayClass4_0.<TryLock>b__0()
   at LiteDB.FileHelper.TryExec(Action action, TimeSpan timeout)
   at LiteDB.StreamExtensions.TryLock(FileStream stream, Int64 position, Int64 length, TimeSpan timeout)
   at LiteDB.FileDiskService.Lock(LockState state, TimeSpan timeout)
   at LiteDB.LockService.Read()
   at LiteDB.LiteEngine.Count(String collection, Query query)
   at LiteDB.LiteCollection`1.Count()

If GetCollection will create new collection, I see no reason why LiteCollection<MyEntity>.Count() should throw such exception ?

LiteDB version 4.1.4
.NET framework 4.7.2

**Comment by JKamsker** [comment]
This is the same problem as #774, which is fixed on the `dev` branch. `dev` ships as the LiteDB 6.x prereleases.

Please try the latest prerelease (currently **6.0.0-prerelease.81**):

```
dotnet add package LiteDB --prerelease
```

If the problem still happens on the prerelease, comment here with the version you used and a repro, and we'll reopen the issue.
