### ISSUE TITLE
v5 Beta - LiteException: Invalid DataPage buffer on 0

### ISSUE THREAD

**Issue by NongBenz** [litedb-org/LiteDB#1374]
Great work on v5 but after a while got this during a routine Upsert call for saving player data and not sure what to look for.

One thing I noticed is that FindByID(x) doesn't seem to work when you have a ulong (SteamID) as the BSON Id. Though FindOne(x => x.ID == steamID)) works fine. Database stores it as Int64 but might be casting to something weird in FindByID. We're switching to string IDs to get around it for now.

LiteException: Invalid DataPage buffer on 0
  at LiteDB.Engine.DataPage..ctor (LiteDB.Engine.PageBuffer buffer) [0x0002b] in <5655f9bdd3d648afba544285415ebde5>:0 
  at LiteDB.Engine.BasePage.ReadPage[T] (LiteDB.Engine.PageBuffer buffer) [0x000b7] in <5655f9bdd3d648afba544285415ebde5>:0 
  at LiteDB.Engine.Snapshot.ReadPage[T] (System.UInt32 pageID) [0x000a6] in <5655f9bdd3d648afba544285415ebde5>:0 
  at LiteDB.Engine.Snapshot.GetPage[T] (System.UInt32 pageID) [0x00017] in <5655f9bdd3d648afba544285415ebde5>:0 
  at LiteDB.Engine.DataService.Delete (LiteDB.Engine.PageAddress blockAddress) [0x00002] in <5655f9bdd3d648afba544285415ebde5>:0 
  at LiteDB.Engine.DataService+<>c__DisplayClass4_0+<<Update>g__source|0>d.MoveNext () [0x001ef] in <5655f9bdd3d648afba544285415ebde5>:0 
  at LiteDB.Engine.BufferWriter.MoveFordward (System.Int32 count) [0x00041] in <5655f9bdd3d648afba544285415ebde5>:0 
  at LiteDB.Engine.BufferWriter.Write (System.Byte value) [0x00012] in <5655f9bdd3d648afba544285415ebde5>:0 
  at LiteDB.Engine.BufferWriter.WriteDocument (LiteDB.BsonDocument value, System.Boolean recalc) [0x0004c] in <5655f9bdd3d648afba544285415ebde5>:0 
  at LiteDB.Engine.DataService.Update (LiteDB.Engine.CollectionPage col, LiteDB.Engine.PageAddress blockAddress, LiteDB.BsonDocument doc) [0x00060] in <5655f9bdd3d648afba544285415ebde5>:0 
  at LiteDB.Engine.LiteEngine.UpdateDocument (LiteDB.Engine.Snapshot snapshot, LiteDB.Engine.CollectionPage col, LiteDB.BsonDocument doc, LiteDB.Engine.IndexService indexer, LiteDB.Engine.DataService data) [0x00055] in <5655f9bdd3d648afba544285415ebde5>:0 
  at LiteDB.Engine.LiteEngine+<>c__DisplayClass29_0.<Upsert>b__0 (LiteDB.Engine.TransactionService transaction) [0x0005d] in <5655f9bdd3d648afba544285415ebde5>:0 
  at LiteDB.Engine.LiteEngine.AutoTransaction[T] (System.Func`2[T,TResult] fn) [0x00033] in <5655f9bdd3d648afba544285415ebde5>:0 
  at LiteDB.Engine.LiteEngine.Upsert (System.String collection, System.Collections.Generic.IEnumerable`1[T] docs, LiteDB.BsonAutoId autoId) [0x0004d] in <5655f9bdd3d648afba544285415ebde5>:0 
  at LiteDB.LiteCollection`1[T].Upsert (System.Collections.Generic.IEnumerable`1[T] documents) [0x00026] in <5655f9bdd3d648afba544285415ebde5>:0 
  at LiteDB.LiteCollection`1[T].Upsert (T document) [0x00013] in <5655f9bdd3d648afba544285415ebde5>:0 
  at BrokeProtocol.Entities.SvPlayer.Save () [0x00581] in <5067e8634c824346a184df1cd5594501>:0 

ps. Small typo on LiteDB.Engine.BufferWriter.MoveFordward

**Comment by webteamby** [comment]
Got the same issue after sequence upsert operations and db file has been grown till 50Gb
**~ERROR~ LiteDB.LiteException: Invalid DataPage buffer on 0
   at LiteDB.Engine.DataPage..ctor(PageBuffer buffer)
   at LiteDB.Engine.BasePage.ReadPage[T](PageBuffer buffer)
   at LiteDB.Engine.Snapshot.ReadPage[T](UInt32 pageID)
   at LiteDB.Engine.Snapshot.GetPage[T](UInt32 pageID)
   at LiteDB.Engine.DataService.Delete(PageAddress blockAddress)
   at LiteDB.Engine.DataService.<>c__DisplayClass4_0.<<Update>g__source|0>d.MoveNext()
   at LiteDB.Engine.BufferWriter.MoveFordward(Int32 count)
   at LiteDB.Engine.BufferWriter.WriteDocument(BsonDocument value, Boolean recalc)
   at LiteDB.Engine.DataService.Update(CollectionPage col, PageAddress blockAddress, BsonDocument doc)
   at LiteDB.Engine.LiteEngine.UpdateDocument(Snapshot snapshot, CollectionPage col, BsonDocument doc, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass29_0.<Upsert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Upsert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Upsert(IEnumerable`1 documents)
   at MigrationLibrary.DAL.Repository.Implementation.UserRepoLiteDb.Upsert(IEnumerable`1 listEntities) in C:\UserRepoLiteDb.cs:line 83**

**Comment by mbdavid** [comment]
Hi @webteamby, your example can be reproduced? I'm fixing some bugs and this bug could be in this fix pack

**Comment by ahmetmeral** [comment]
Hi @mbdavid  
I caught a similar mistake. Log in attachment file
[data-log.zip](https://github.com/mbdavid/LiteDB/files/4035105/data-log.zip)

**Comment by mbdavid** [comment]
Hi, there was a bug page addresses that I fix in current master branch. Can you test again if will occurs again (need re-create your database because I change data file structure to fix this)

**Comment by maxbl4** [comment]
This test https://github.com/maxbl4/RaceLogic/blob/1e29a4ce5f3b127cbe328a195db56bab525aaa7b/Tests/CheckpointService/Storage/StorageServiceTests.cs#L181
has about 20% chance to reproduce this bug, just run it several times, or the whole test class

**Comment by maxbl4** [comment]
> Hi, there was a bug page addresses that I fix in current master branch. Can you test again if will occurs again (need re-create your database because I change data file structure to fix this)

Can you create a new release with this fix, like 5.0.1-alpha ?

**Comment by JensSchadron** [comment]
@maxbl4 A new version has been created in the meantime (the RC), could you try and see if your issue still in there? Please keep in mind that the datafile format is incompatible due to the change the David spoke of.
You can close this ticket if your issue has been resolved :)

**Comment by maxbl4** [comment]
@JensSchadron Hello, updated to 5.0-rc, now it is even worse :( Not only the original error is still reproducible, but for some reason support for ConnectionString.UtcDate was dropped. This breaks many of my tests and logic of application

**Comment by Tirraon** [comment]
@maxbl4 
UtcDate was moved to pragmas.

**Comment by Lupinho** [comment]
I have the sam issue with 5.0-rc after inserting some data into my db:
`LiteDB.LiteException:` Invalid IndexPage buffer on 0
   at LiteDB.Engine.IndexPage..ctor(PageBuffer buffer)
   at LiteDB.Engine.BasePage.ReadPage[T](PageBuffer buffer)
   at LiteDB.Engine.Snapshot.ReadPage[T](UInt32 pageID, FileOrigin& origin, Int64& position, Int32& walVersion)
   at LiteDB.Engine.Snapshot.GetPage[T](UInt32 pageID, FileOrigin& origin, Int64& position, Int32& walVersion)
   at LiteDB.Engine.IndexService.Find(CollectionIndex index, BsonValue value, Boolean sibling, Int32 order)
   at LiteDB.Engine.IndexEquals.<Execute>d__3.MoveNext()
   at LiteDB.Engine.BasePipe.<LoadDocument>d__9.MoveNext()
   at LiteDB.Engine.BasePipe.<Include>d__10.MoveNext()
   at LiteDB.Engine.BasePipe.<Filter>d__11.MoveNext()
   at LiteDB.Engine.BasePipe.<Filter>d__11.MoveNext()
   at LiteDB.Engine.QueryPipe.<Select>d__2.MoveNext()
   at `LiteDB.Engine.QueryExecutor.<>c__DisplayClass10_0.<<ExecuteQuery>g__RunQuery`

**Comment by maxbl4** [comment]
Hi @Tirraon , can you elaborate? Is it possible to store UTC dates in 5-rc and how?

**Comment by lbnascimento** [comment]
@maxbl4 Internally, all dates are stored in UTC. The option to display them as UTC or convert them to local time upon retrieval is now a pragma, which means it is stored in the header of the datafile and no longer defined in the connection string.

You can set the UTC_DATE pragma to true with the following command:

```C#
using (var db = new LiteDatabase("data.db")
{
	db.Pragma("UTC_DATE", true);
}
```

**Comment by Lupinho** [comment]
I can reproduce this bug (Invalid IndexPage buffer on 0) also easily in V5 final. This is a major issue! So LiteDB is not usable anymore! V4 did this job without problems. I just insert some thousend documents into a collection (that has 5 indexes defined).
At this time I have to say: LiteDB is completely unusable, because inserting small documents into an empty database should not be too difficult and cannot be workaround!!

**Comment by Lupinho** [comment]
Now I also get this on a test case:
LiteDB.LiteException
  HResult=0x80131500
  Message=Invalid IndexPage buffer on 1682
  Source=LiteDB
  StackTrace:
   at LiteDB.Engine.IndexPage..ctor(PageBuffer buffer)
   at LiteDB.Engine.BasePage.ReadPage[T](PageBuffer buffer)
   at LiteDB.Engine.Snapshot.ReadPage[T](UInt32 pageID, FileOrigin& origin, Int64& position, Int32& walVersion)
   at LiteDB.Engine.Snapshot.GetPage[T](UInt32 pageID, FileOrigin& origin, Int64& position, Int32& walVersion)
   at LiteDB.Engine.IndexService.Find(CollectionIndex index, BsonValue value, Boolean sibling, Int32 order)
   at LiteDB.Engine.IndexEquals.<Execute>d__3.MoveNext()
   at LiteDB.Engine.BasePipe.<LoadDocument>d__6.MoveNext()
   at LiteDB.Engine.BasePipe.<Filter>d__8.MoveNext()
   at LiteDB.Engine.QueryPipe.<Select>d__2.MoveNext()
   at LiteDB.Engine.QueryExecutor.<>c__DisplayClass10_0.<<ExecuteQuery>g__RunQuery|0>d.MoveNext()
   at LiteDB.BsonDataReader..ctor(IEnumerable`1 values, String collection)
   at LiteDB.Engine.QueryExecutor.ExecuteQuery(Boolean executionPlan)
   at LiteDB.Engine.QueryExecutor.ExecuteQuery()
   at LiteDB.Engine.LiteEngine.Query(String collection, Query query)
   at LiteDB.LiteQueryable`1.<ToDocuments>d__26.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Lupinho.Net.HardlinkBackup.Engine.DS.DBIndex.DBDataStoreIndex.GetIndexFileVersion(String fullName, DateTime versionTime, Int64 fileLength, Byte[] checksum, Boolean includeUsedBy) in C:\Users\twolf\Workspaces\Lupinho.Net\trunk\HardlinkBackup\Lupinho.Net.HardlinkBackup.Engine\DS\DBIndex\DBDataStoreIndex.cs:line 637
   at Lupinho.Net.HardlinkBackup.Engine.DS.DBIndex.DBDataStoreIndex.AddUsedBy(IFileVersion fileVersion, Guid backupSetId, String[] alternativeDataStreamNames) in C:\Users\twolf\Workspaces\Lupinho.Net\trunk\HardlinkBackup\Lupinho.Net.HardlinkBackup.Engine\DS\DBIndex\DBDataStoreIndex.cs:line 878
   at Lupinho.Net.HardlinkBackup.Engine.Test.DS.DataStoreIndexTest.TestScanIndexPerformance() in C:\Users\twolf\Workspaces\Lupinho.Net\trunk\HardlinkBackup\Lupinho.Net.HardlinkBackup.Engine.Test\DS\DataStoreIndexTest.cs:line 201

  This exception was originally thrown at this call stack:
	LiteDB.Engine.IndexPage.IndexPage(LiteDB.Engine.PageBuffer)
	LiteDB.Engine.IndexService.Find(LiteDB.Engine.CollectionIndex, LiteDB.BsonValue, bool, int)
	LiteDB.Engine.IndexEquals.Execute(LiteDB.Engine.IndexService, LiteDB.Engine.CollectionIndex)
	LiteDB.Engine.BasePipe.LoadDocument(System.Collections.Generic.IEnumerable<LiteDB.Engine.IndexNode>)
	LiteDB.Engine.BasePipe.Filter(System.Collections.Generic.IEnumerable<LiteDB.BsonDocument>, LiteDB.BsonExpression)
	LiteDB.Engine.QueryPipe.Select(System.Collections.Generic.IEnumerable<LiteDB.BsonDocument>, LiteDB.BsonExpression)
	LiteDB.Engine.QueryExecutor.ExecuteQuery.__RunQuery|0()
    ...
    [Call Stack Truncated]

**Comment by Lupinho** [comment]
Ok, I get some light into these issues: I think, these errors are provocated by a multi-threading issue. Because of the lack of insert performance of LiteDB I build a cache for objects to insert. If flushing this cache (doing bulk inserts) asynchronously while querying for them using indexes, this error occurred. If I wait for flushing finished before querying the collection, the error does not occurre.

**Comment by maxbl4** [comment]
Upgraded to 5.0.2. The test same test still fails from time to time, but it has different error:
```
System.ArgumentException : Invalid LCID code
   at LiteDB.LCID.GetCulture(Int32 lcid)
   at LiteDB.Collation..ctor(Int32 lcid, CompareOptions sortOptions)
   at LiteDB.Engine.EnginePragmas.<.ctor>b__36_7(BufferSlice b)
   at LiteDB.Engine.EnginePragmas..ctor(BufferSlice buffer, HeaderPage headerPage)
   at LiteDB.Engine.HeaderPage.LoadPage()
   at LiteDB.Engine.WalIndexService.RestoreIndex(HeaderPage& header)
   at LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
   at LiteDB.ConnectionString.CreateEngine()
   at LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)
   at LiteDB.LiteDatabase..ctor(String connectionString, BsonMapper mapper)
   at LiteDB.LiteRepository..ctor(String connectionString, BsonMapper mapper)
```

Otherwise everything works, I have used @lbnascimento comment about pragmas - thanks. What would be great is a way to set default pragmas during starup, and make some way to set them in a type safe, compile time checked way, not with simple strings.

**Comment by maxbl4** [comment]
Looks like the new exception was side effect of version change on first run. Now I see the same error again
```
LiteDB.LiteException : Invalid DataPage buffer on 0
   at LiteDB.Engine.DataPage..ctor(PageBuffer buffer)
   at LiteDB.Engine.BasePage.ReadPage[T](PageBuffer buffer)
   at LiteDB.Engine.Snapshot.ReadPage[T](UInt32 pageID, FileOrigin& origin, Int64& position, Int32& walVersion)
   at LiteDB.Engine.Snapshot.GetPage[T](UInt32 pageID, FileOrigin& origin, Int64& position, Int32& walVersion)
   at LiteDB.Engine.Snapshot.GetFreeDataPage(Int32 bytesLength)
   at LiteDB.Engine.DataService.<>c__DisplayClass3_0.<<Insert>g__source|0>d.MoveNext()
   at LiteDB.Engine.BufferWriter..ctor(IEnumerable`1 source)
   at LiteDB.Engine.DataService.Insert(BsonDocument doc)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at LiteDB.LiteRepository.Insert[T](T entity, String collectionName)
```

What I should mention, is the nature of my test. Basically it will create file data-001.litedb, put one record there, then open the file again and try to read the record into not compatible object to get an error. My repository code should catch the error, add new sequence number to the file name and try to open data-002.litedb. 
I get a failure, when I run the test second time. My test code would find and remove all data files before the test start, I have asserts for that before constructing LiteRepository, but it does not delete -log file. Maybe something has to do with the left over litedb log file?

**Comment by maxbl4** [comment]
Yes, I have update my test code to also delete litedb log file and now test is green every time. Looks like there should a check, when litedb creates new database file, that there is already a log file and it is has incompatible data

**Comment by mbdavid** [comment]
Hi @maxbl4, v5-rc datafiles are not compatible with final v5. Datafile structure was changed. You need recreate your database. If you error presist, please open another issue to be better and simple to track.

**Comment by nabeelio** [comment]
I'm (well, clients) are seeing this intermittently on 5.0.1:

```
Package: Acars
Version: 1.0.0.821
OS: WINDOWS
Windows: 10.0.18363
Date: 2020-02-21T01:17:29.4764536Z

Exception Stack:
LiteDB.LiteException: Invalid IndexPage buffer on 0
  at LiteDB.Engine.IndexPage..ctor(PageBuffer buffer)
  at LiteDB.Engine.BasePage.ReadPage[T](PageBuffer buffer)
  at LiteDB.Engine.Snapshot.ReadPage[T](UInt32 pageID, FileOrigin& origin, Int64& position, Int32& walVersion)
  at LiteDB.Engine.Snapshot.GetPage[T](UInt32 pageID, FileOrigin& origin, Int64& position, Int32& walVersion)
  at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte level, IndexNode last)
  at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, IndexNode last)
  at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
  at LiteDB.Engine.LiteEngine.<>c__DisplayClass30_0.<Upsert>b__0(TransactionService transaction)
  at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
  at LiteDB.LiteCollection`1.Upsert(T entity)
  at Acars.SimObjects.AirportDatabase.Save()
  at Acars.ViewModels.SettingsViewModel.<ResyncScenery>b__37_0()
  at System.Threading.Tasks.Task.Execute()
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Acars.ViewModels.SettingsViewModel.<ResyncScenery>d__37.MoveNext()
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
  at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
  at System.Windows.Threading.DispatcherOperation.InvokeImpl()
  at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
  at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
  at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
  at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
  at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
  at System.Windows.Threading.DispatcherOperation.Invoke()
  at System.Windows.Threading.Dispatcher.ProcessQueue()
  at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
  at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
  at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
  at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
  at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
  at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
  at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
  at System.Windows.Application.RunDispatcher(Object ignore)
  at System.Windows.Application.RunInternal(Window window)
  at Acars.App.Main()
```

**Comment by mbdavid** [comment]
@nabeelio, could you please open an bug report about this? It's important to know if database was created/populated in v5.01+. If you have a complex system, can you explain me how threads/data are inserted/updates/deleted?

**Comment by nabeelio** [comment]
@mbdavid Sure, I can do that, I'm trying to see if I get anymore crash reports. Let me try to gather some more information. The DB was created on 5.0.1, AKAIK. I haven't used the beta versions. I'm still trying to replicate it on my side. It is running inside an `async` block, but there is a lock around it.

**Comment by mbdavid** [comment]
Hi @nabeelio, that's very important for LiteDB. Any bug that can corrupt database is my TOP priority. If you get again, open that I will take a closer look. Thanks.

**Comment by JKamsker** [comment]
Closing this as a duplicate of #1690. The only trigger we could reproduce on the current `dev` (6.x prerelease) is a reader opening a collection while another thread's first write is still creating it, which fails with the same page-type errors ("Invalid Collection …" / "page type must be collection page"). That race is tracked in #1690, which stays open.

If you still hit the Index/Data-page variant on the latest prerelease without collections being created concurrently, comment here with a repro and we'll reopen it.
