### ISSUE TITLE
System.NotImplementedException: The method or operation is not implemented

### ISSUE THREAD

**Issue by webteamby** [litedb-org/LiteDB#1392]
Got this error in **v.5.0.0-beta**:

_System.NotImplementedException: The method or operation is not implemented.
   at LiteDB.BufferSliceExtensions.ReadIndexKey(BufferSlice buffer, Int32 offset)
   at LiteDB.Engine.IndexNode..ctor(IndexPage page, Byte index, BufferSlice segment)
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte level, IndexNode last)
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, IndexNode last)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass29_0.<Upsert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at MigrationLibrary.DAL.Repository.Implementation.UserRepoLiteDb.Upsert(IEnumerable`1 listEntities) in C:\src\UserRepoLiteDb.cs:line 86_

**Comment by webteamby** [comment]
**System.NotImplementedException: The method or operation is not implemented.**
   at LiteDB.BufferSliceExtensions.ReadIndexKey(BufferSlice buffer, Int32 offset)
   at LiteDB.Engine.IndexNode..ctor(IndexPage page, Byte index, BufferSlice segment)
   at LiteDB.Engine.IndexService.Find(CollectionIndex index, BsonValue value, Boolean sibling, Int32 order)
   at LiteDB.Engine.IndexEquals.Execute(IndexService indexer, CollectionIndex index)+MoveNext()
   at LiteDB.Engine.BasePipe.LoadDocument(IEnumerable`1 nodes)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at LiteDB.BsonExpression.Execute(IEnumerable`1 source)
   at LiteDB.Engine.QueryPipe.SelectAll(IEnumerable`1 source, BsonExpression select)+MoveNext()
   at LiteDB.Engine.QueryExecutor.<>c__DisplayClass9_0.<<ExecuteQuery>g__RunQuery|0>d.MoveNext()
   at LiteDB.BsonDataReader..ctor(IEnumerable`1 values, String collection)
   at LiteDB.Engine.QueryExecutor.ExecuteQuery(Boolean executionPlan)
   at LiteDB.Engine.LiteEngine.Query(String collection, Query query)
   at LiteDB.LiteQueryable`1.ToDocuments()+MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at LiteDB.LiteQueryable`1.Exists()
   at MigrationLibrary.DAL.Repository.Implementation.UserRepoLiteDb.Exists(Expression`1 filter)

**Comment by JensSchadron** [comment]
Hi @webteamby ,

Thanks for reporting both exceptions.
I don't know if you had a way to reproduce those errors, but if so, could you please try doing it again using the latest v5 RC? Thanks in advance.

**Comment by DennisAMenace** [comment]
I am getting this error with 5.0.9 that is similar to OP's error.

```
---> System.NotImplementedException: The method or operation is not implemented.
   at LiteDB.BufferSliceExtensions.ReadIndexKey(BufferSlice buffer, Int32 offset)
   at LiteDB.Engine.IndexNode..ctor(IndexPage page, Byte index, BufferSlice segment)
   at LiteDB.Engine.IndexService.GetNodeList(PageAddress nodeAddress)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at LiteDB.Engine.LiteEngine.UpdateDocument(Snapshot snapshot, CollectionPage col, BsonDocument doc, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass30_0.<Upsert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
```

My database size is 38.2 MB

My litedb file opens fine in LiteDB Studio.

This error occured when `.Upsert` was called on my `ILiteCollection<MyClass>` object.

**Comment by sondreb** [comment]
This error still happens in the latest main repo source. The helper that get the Bson Type returns the value of 59 (in my instance here), which does not parse to any known type in the enum.

![image](https://user-images.githubusercontent.com/309938/103029871-f84b7500-455a-11eb-8e88-b2c51e74f18a.png)

This is the method call that returns 59:

```
ExtendedLengthHelper.ReadLength(buffer[offset++], buffer[offset], out var type, out var len);
```

The offset value is 13:

![image](https://user-images.githubusercontent.com/309938/103030069-59734880-455b-11eb-8e93-636943c98494.png)

This probably doesn't say much but:

![image](https://user-images.githubusercontent.com/309938/103030131-7576ea00-455b-11eb-95b4-9cc19685421e.png)

**Comment by sondreb** [comment]
This still happens with the latest code from master, which includes an corruption fix that was added recently (https://github.com/mbdavid/LiteDB/commit/26bdeb673d95ca6078a4ed12a0f7ffc8d22e50a9)

**Comment by JKamsker** [comment]
This `NotImplementedException` in `ReadIndexKey` means the engine read an index node with an invalid key type byte (the debugging above found type 59), so the index page was already damaged when it was read. That throw site is unchanged in the current code. We couldn't recreate the underlying corruption, though, including a heavy parallel `FindOne`/`Upsert` run on the 6.x prerelease.

What would help most:
- a datafile that shows the error, if it can be shared
- LiteDB version, connection string (Direct or Shared), and whether several threads or processes write at the same time
- whether it still happens on the latest prerelease (`dotnet add package LiteDB --prerelease`) after a `db.Rebuild()`

We'll keep this issue open and also try to reproduce it on our side.

**Update:** We built our own databases to try to trigger this and haven't reproduced it yet. We ran heavy parallel `Upsert`/`Exists`/`FindById` load on one instance, four processes in Shared mode, a writer killed in the middle of large `Upsert` batches, and a 1M-document database with 48 readers and a writer. We also restored a backup `.db` while a leftover `-log.db` stayed in place. Some of these damaged the index ("page type must be index page", "pages in memory store must be non-shared"), but none gave this `NotImplementedException` in `ReadIndexKey`.

What would help most is a database that throws it, `.db` and `-log.db` zipped together, plus the LiteDB version and connection string. This issue stays open.

The same `ReadIndexKey` symptom is also listed in #2817 (a cache race under parallel reads), which is the likeliest cause; if your app reads from several threads, please mention it.
