### ISSUE TITLE
Corrupted database, error when trying to read one of the tables

### ISSUE THREAD

**Issue by Tumist76** [litedb-org/LiteDB#1399]
I have a database with 4 tables. When my app is trying to read one of the tables, it throws the exception. I tried to open my DB with LiteDB.Studio (version with LiteDB 4) and it opens everything flawlessly. Studio rewrites my DB file, i feed it to my app and get an error that it's not a proper DB file. What am I doing wrong. How can I restore my DB?

**Table reading exception log:**

```
System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.DataPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.QueryCursor.Fetch(TransactionService trans, DataService data)
   at LiteDB.LiteEngine.<Find>d__9.MoveNext()
   at LiteDB.LiteEngine.<Find>d__13.MoveNext()
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
```

**Comment by JensSchadron** [comment]
This is sadly an issue regarding an edge case which we don't know how to reproduce (yet), but we hope to have it solved with the rewrite of LiteDB in the upcoming v5. However, there's a static recovery method available in the source code which you can give a try (It's in the v4 branch).

**Comment by JKamsker** [comment]
The `EmptyPage` → `DataPage` cast means one collection's page chain in the v4 file points at a page that isn't a data page. It's usually left behind by a write that failed or was interrupted. One concrete v4 cause is in #1115: a custom `Logger` that threw while logging an error skipped the rollback, and the dirty pages were saved later. v4 is no longer maintained.

Since v5.0 this is handled differently. A failed transaction is always rolled back, and uncommitted pages never reach the data file: commits are appended to a `-log` file ([DiskService.cs](https://github.com/litedb-org/LiteDB/blob/47268cb4/LiteDB/Engine/Disk/DiskService.cs#L167)) and copied in at checkpoint. Page types are validated on read ([DataPage.cs](https://github.com/litedb-org/LiteDB/blob/47268cb4/LiteDB/Engine/Pages/DataPage.cs#L17)), and a mismatch throws `LiteException` 999, which `auto-rebuild=true` repairs on the next open.

To recover your data, open a copy of the file with `Upgrade=true`. That reads the documents into a new v5 file and recreates all indexes. Please try the latest prerelease:

```
dotnet add package LiteDB --prerelease
```

If this doesn't cover your case, comment here and we'll reopen it.
