### ISSUE TITLE
[BUG] System.InvalidOperationException on insert/query

### ISSUE THREAD

**Issue by Lupinho** [litedb-org/LiteDB#1472]
LiteDB 5.0.2

Now I get this error:

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at LiteDB.BsonDocument.CopyTo(BsonDocument other)
   at LiteDB.Engine.IndexCost..ctor(CollectionIndex index, BsonExpression expr, BsonExpression value, Collation collation)
   at LiteDB.Engine.QueryOptimization.ChooseIndex(HashSet`1 fields)
   at LiteDB.Engine.QueryOptimization.DefineIndex()
   at LiteDB.Engine.QueryOptimization.ProcessQuery()
   at LiteDB.Engine.QueryExecutor.<>c__DisplayClass10_0.<<ExecuteQuery>g__RunQuery

This must be multithreading issue. I bulk-insert many documents while querying the same collection.

**Comment by mbdavid** [comment]
Hi @Lupinho, can you paste your unit test code to check this?

**Comment by Lupinho** [comment]
At this time I have no unit test for this error. Anyway I can't get around this error in my application and so LiteDB is not useable for me in this state. The situation is the same as in the other error I reported, which was fixed: I bulk-insert many documents while querying at the same collection. I have only two collections, where one is DbRef-ed by the other.
For me the error looks like a Bson-Document is read out (BsonDocument.CopyTo), while another thread modified the same Bson-Document (in the update thread).

**Comment by Lupinho** [comment]
Test-wise I build in a retry to BsonDocument.CopyTo; this seemed to work. Synchronizing the access to the Dictionary did nit work on first try and may slow down normal access. But I dont know why there is concurrency on these documents and what is the concept in LiteDB to deal with concurrency.

**Comment by Lupinho** [comment]
I could not reproduce the original exception with the current release (5.0.5). But: now I get the same error on disposing:
`System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at LiteDB.Engine.Snapshot.<GetWritablePages>d__22.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at LiteDB.Engine.DiskService.DiscardCleanPages(IEnumerable`1 pages)
   at LiteDB.Engine.TransactionService.Dispose()
   at LiteDB.Engine.TransactionMonitor.Dispose()
   at LiteDB.Engine.LiteEngine.Dispose(Boolean disposing)
   at LiteDB.Engine.LiteEngine.Dispose()
   at LiteDB.LiteDatabase.Dispose(Boolean disposing)
   at LiteDB.LiteDatabase.Dispose()
   at Lupinho.Net.HardlinkBackup.Engine.DS.DBIndex.DBDataStoreIndex.Dispose()
   at Lupinho.Net.HardlinkBackup.Engine.DS.DataStore.UploadInt(Boolean reopen)`

**Comment by lbnascimento** [comment]
@Lupinho v5.0.7 was released earlier this week, could you test with it?

**Comment by Lupinho** [comment]
If tested with 5.0.7 also. The problem seems to be provocated on my side: I think I did queries in parallel when disposing the Database. Decide, if the exception above is fine in this case; I would rather have seen something like a message "rejected query on a data base while disposing" or similar...

**Comment by leandromolina** [comment]
hi, i am facing the exact same problem when i try to bulk insert documents into a collection, both from different threads and from the same thread. It's honestly a shame because this bug renders LiteDB unusable in my project.
No solution yet?

**Comment by ryancheung** [comment]
I'm facing this issue too. If `InsertBulk` documents with emberred documents, it raises exception:
```
发生异常: CLR/System.InvalidOperationException
“System.InvalidOperationException”类型的未经处理的异常在 System.Private.CoreLib.dll 中发生 : 'Collection was modified; enumeration operation may not execute.'
   在 System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   在 System.Collections.Generic.List`1.Enumerator.MoveNext()
   在 System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   在 LiteDB.BsonMapper.SerializeObject(Type type, Object obj, Int32 depth)
   在 LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)
   在 LiteDB.BsonMapper.ToDocument(Type type, Object entity)
   在 LiteDB.BsonMapper.ToDocument[T](T entity)
   在 LiteDB.LiteCollection`1.Insert(T entity)
```

I'm in single-threaded mode.

**Comment by vecalion** [comment]
Experiencing the same issue in my project. Not constantly repeatable, appears randomly:

```
BsonMapper.SerializeArray (System.Type type, System.Collections.IEnumerable array, System.Int32 depth)
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

System.Collections.Generic
List`1+Enumerator[T].MoveNextRare ()
System.Collections.Generic
List`1+Enumerator[T].MoveNext ()
BsonMapper.SerializeArray (System.Type type, System.Collections.IEnumerable array, System.Int32 depth)
BsonMapper.Serialize (System.Type type, System.Object obj, System.Int32 depth)
BsonMapper.SerializeObject (System.Type type, System.Object obj, System.Int32 depth)
BsonMapper.Serialize (System.Type type, System.Object obj, System.Int32 depth)
BsonMapper.ToDocument (System.Type type, System.Object entity)
BsonMapper.ToDocument[T] (T entity)
LiteCollection`1[T].Insert (T entity)
```

**Comment by JKamsker** [comment]
Closing because this doesn't reproduce on current `dev`, and no single commit fixes it. Since this was reported, transaction admission and query leases have been rewritten (1b6971304, #2790), and the storage and transaction fixes from #2918 landed.

Tried on `dev` @ faad53821:
- one `InsertBulk` writer plus 6 threads running indexed queries and counts, 5 s: about 29,500 documents, 0 errors.
- disposing the database while 4 threads query and insert, 10 rounds: no `InvalidOperationException` ("Collection was modified").

If you can still trigger it on a current prerelease, please reopen with a repro.
