### ISSUE TITLE
function.Invoke in LiteCollection<T>.Find

### ISSUE THREAD

**Issue by SlaskoCZ** [litedb-org/LiteDB#1502]
**Version**
5.0.2

**Describe the bug**
While trying to upgrade from v4 to v5, i found out that function can no longer be invoked in Find Expression.

**Code to Reproduce**
```
var logs = GetLogs(x => x.ConnectorId == connector.Id && x.Enabled == true);

        public IEnumerable<Log> GetLogs(Func<Log, bool> function)
        {
            var connectors = database.GetCollection<Log>(Database.Types.Log.TableName);
            return connectors.Find(x=> function.Invoke(x)).OrderByDescending(x => x.LogDate);
        }
```

**Expected behavior**
Same as in v4 where it worked. Should work same as in v5 alternative:
```
var query = Query.And(Query.EQ("ConnectorId", connector.Id), Query.EQ("Enabled", true))
var logs = GetLogs(query);
        public IEnumerable<Log> GetLogs(BsonExpression expression)
        {
            var connectors = database.GetCollection<Log>(Database.Types.Log.TableName);
            return connectors.Find(expression).OrderByDescending(x => x.LogDate);
        }
```

**Screenshots/Stacktrace**
```
System.NotSupportedException: Method Invoke not available to convert to BsonExpression (value(ConnectorMonitor.Models.Providers.LiteDbLogProvider+<>c__DisplayClass5_0).function.Invoke(x)).
   at LiteDB.LinqExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at LiteDB.LinqExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at LiteDB.LinqExpressionVisitor.Resolve(Boolean predicate)
   at LiteDB.LiteCollection`1.Find(Expression`1 predicate, Int32 skip, Int32 limit)
   at ConnectorMonitor.Models.Providers.LiteDbLogProvider.GetLogs(Func`2 function) in C:\Work\ConnectorMonitor\ConnectorMonitor\Models\Providers\LiteDbLogProvider.cs:line 61
```

**Additional context**
Can add rest of the code if needed. Bug looks to be easily reproduced with code i provided
ConnectorId is PK System.Guid

**Comment by mbdavid** [comment]
Hi @SlaskoCZ, in v4, when you write an LINQ expressions that can't be converted into database query, LiteDB just execute as LINQ to Object (after result from database). It's just IEnumerable LINQ command.

In v5 (current 5.0.2 version) this feature does not exists. All LINQ expressions must be converted into BsonExpression. When is not possible convert a error message is throw. This will be "fix" in next v5.1 version...

**Comment by SlaskoCZ** [comment]
Ok, thank, should i close this, or keep it open as reference for future feature?

**Comment by mbdavid** [comment]
I link this issue with my project boarding for v5.1. I will close when finish next version.

**Comment by JKamsker** [comment]
Consolidated into #2783, which combines this report with the related ones and tracks the fix. Closing this as a duplicate — please follow #2783, and comment there if your case is different.
