### ISSUE TITLE
[BUG] v4 version NullReferenceException on FindById() method.

### ISSUE THREAD

**Issue by NikasZalias** [litedb-org/LiteDB#1652]
**Version**
4.1.4

**Describe the bug**
Calling FindById() method sometimes throw NullReferenceException. 

**Code to Reproduce**
` 
_db = new LiteDatabase($"Filename={FILENAME}");
  _db.GetCollection("NAME").FindById(ID);
`

**Expected behavior**
Not to crash.

**Screenshots/Stacktrace**

> System.NullReferenceException: Object reference not set to an instance of an object.
at LiteDB.LiteEngine..ctor(IDiskService disk, string password, Nullable<T> timeout, int cacheSize, Logger log, bool utcDate)
at LiteDB.LiteDatabase+<>c__DisplayClass11_0.<.ctor>b__0()
at LiteDB.LazyLoad<T>.get_Value()
at LiteDB.LiteCollection<T>+<Find>d__17.MoveNext()
at System.Linq.Enumerable.SingleOrDefault<TSource>(IEnumerable<T> source)
at LiteDB.LiteCollection<T>.FindById(BsonValue id)

**Additional context**
Not sure why or when it happens, but for now this is a major issue in my application. I can't reproduce it, but I can see that users experience this issue...

Is there a way to fix it? And does this exception occurs in v5, cause I'm currently migrating and just want to know if this will happen again and if yes, I would like to know how to prevent it.

**Comment by lbnascimento** [comment]
@NikasZalias Any other info to help reproduce the bug, like platform, datafile being used and queries being used?

**Comment by NikasZalias** [comment]
@lbnascimento The platform is **.NET Framework 4.6.1**. I don't have the data file that the user has used and no queries been made. It's just this line that breaks... Also, OS that has a crash is **Windows NT 6.2.#.#**. I wish I could have more data, but that's it...

**Comment by JKamsker** [comment]
We checked the 4.1.4 code for this stack. The `LiteEngine` constructor reads page 0 of the file, casts it to the header page and reads the password from it right away. If page 0 isn't a valid header, for example because the file is zero-filled, truncated or damaged after a power loss or a crash while it was being created, that cast returns `null` and you get exactly this `NullReferenceException`. `FindById` only shows up in the stack because it's the first call and opens the engine lazily.

So this points to a damaged data file on those machines, not to `FindById` itself. v4 is no longer maintained.

To your v5 question: v5 and later validate the header when opening and throw `LiteException` "invalid database" for a bad file instead of an NRE, so you can catch it and handle it, e.g. by restoring a backup. When you migrate, open the old file once with `Upgrade=true` in the connection string to convert it.

If this doesn't cover your case, comment here and we'll reopen it.
