### ISSUE TITLE
[BUG] corrupted collections on azure web app

### ISSUE THREAD

**Issue by henon** [litedb-org/LiteDB#1653]
**Version**
v5.0.7

**Describe the bug**
A specific collection gets corrupted and trying to access it throws this:

********************************************************************************
LiteException: "Invalid Collection on 0. Full zero: True. Page Type: Empty. Prev/Next: 0/0. UniqueID: 84. ShareCounter: 1. "
--------------------------------------------------------------------------------
     at LiteDB.Engine.CollectionPage..ctor(PageBuffer buffer)
     at LiteDB.Engine.BasePage.ReadPage[T](PageBuffer buffer)
     at LiteDB.Engine.Snapshot.ReadPage[T](UInt32 pageID, FileOrigin& origin, Int64& position, Int32& walVersion)
     at LiteDB.Engine.Snapshot.GetPage[T](UInt32 pageID, FileOrigin& origin, Int64& position, Int32& walVersion)
     at LiteDB.Engine.CollectionService.Get(String name, Boolean addIfNotExists, CollectionPage& collectionPage)
     at LiteDB.Engine.Snapshot..ctor(LockMode mode, String collectionName, HeaderPage header, UInt32 transactionID, TransactionPages transPages, LockService locker, WalIndexService walIndex, DiskReader reader, Boolean addIfNotExists)
     at LiteDB.Engine.TransactionService.<CreateSnapshot>g__create|42_0(<>c__DisplayClass42_0& )
     at LiteDB.Engine.TransactionService.CreateSnapshot(LockMode mode, String collection, Boolean addIfNotExists)
     at LiteDB.Engine.QueryExecutor.<>c__DisplayClass10_0.<<ExecuteQuery>g__RunQuery|0>d.MoveNext()
     at LiteDB.BsonDataReader..ctor(IEnumerable`1 values, String collection)
     at LiteDB.Engine.QueryExecutor.ExecuteQuery(Boolean executionPlan)
     at LiteDB.Engine.QueryExecutor.ExecuteQuery()
     at LiteDB.Engine.LiteEngine.Query(String collection, Query query)
     at LiteDB.LiteQueryable`1.ToDocuments()+MoveNext()
     at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
...
********************************************************************************

It might have to do with https://github.com/mbdavid/LiteDB/issues/1622 which I also experience or it might have to do with concurrent multi-threaded access to the collection. 

**Code to Reproduce**
Can not be reproduced, but happened to me only on Azure, but there it happened very frequently, so it really looks like being caused by this issue: https://github.com/mbdavid/LiteDB/issues/1622

**Comment by JKamsker** [comment]
Consolidated into #2792, which combines this report with the related ones and tracks the fix. Closing this as a duplicate — please follow #2792, and comment there if your case is different.
