### ISSUE TITLE
[BUG] UWP Release Mode calling EnsureIndex throws "Invalid Collection"

### ISSUE THREAD

**Issue by enghch** [litedb-org/LiteDB#1690]
**Version**
LiteDB 5.0.7 and 5.0.8 / Windows 10 Version 10.0.18363 Build 18363 / .NET Core UWP
UWP x86 Release mode

**Describe the bug**
Creating and saving to the LiteDB database works great in my app when compiled for x86 Debug mode. But when I change it to a Release build I get this error when call EnsureIndex:

> {"Invalid Collection on 0. Full zero: True. Page Type: Empty. Prev/Next: 0/0. UniqueID: 1. ShareCounter: -1. "}

 ```
 at LiteDB.Engine.CollectionPage..ctor(PageBuffer buffer)
   at LiteDB.Engine.BasePage.ReadPage[T](PageBuffer buffer)
   at LiteDB.Engine.Snapshot.ReadPage[T](UInt32 pageID, FileOrigin& origin, Int64& position, Int32& walVersion)
   at LiteDB.Engine.Snapshot.GetPage[T](UInt32 pageID, FileOrigin& origin, Int64& position, Int32& walVersion)
   at LiteDB.Engine.CollectionService.Get(String name, Boolean addIfNotExists, CollectionPage& collectionPage)
   at LiteDB.Engine.Snapshot..ctor(LockMode mode, String collectionName, HeaderPage header, UInt32 transactionID, TransactionPages transPages, LockService locker, WalIndexService walIndex, DiskReader reader, Boolean addIfNotExists)
   at LiteDB.Engine.TransactionService.<CreateSnapshot>g__create|42_0(<>c__DisplayClass42_0& )
   at LiteDB.Engine.TransactionService.CreateSnapshot(LockMode mode, String collection, Boolean addIfNotExists)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass5_0.<EnsureIndex>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.EnsureIndex(String collection, String name, BsonExpression expression, Boolean unique)
   at LiteDB.LiteCollection`1.EnsureIndex(String name, BsonExpression expression, Boolean unique)
   at LiteDB.LiteCollection`1.EnsureIndex(BsonExpression expression, Boolean unique)
   at LiteDB.LiteCollection`1.EnsureIndex[K](Expression`1 keySelector, Boolean unique)
```

**Code to Reproduce**
```
            db = new LiteDatabase(Path);

            // Get a collection (create it if it doesn't exist)
            ScenesCollection = db.GetCollection<Scene>(COLLECTION_SCENES);
            ScenesCollection.EnsureIndex(x => x.Name);
```

**Expected behavior**
It should have silently created the index.

**Comment by lbnascimento** [comment]
@enghch Could you provide the datafile you're using?

**Comment by enghch** [comment]
Sure! Here it is zipped up. The log file is zero bytes. 

[movie.lite-log.zip](https://github.com/mbdavid/LiteDB/files/4644791/movie.lite-log.zip)

**Comment by lbnascimento** [comment]
@enghch I could not reproduce the issue with a Windows .NET Core app (and I don't have the UWP modules installed currently), but I suspect it has something to do with that zero-byte log file. Try deleting it and see what happens - or even better, create a new instance of `LiteDatabase` with `using`.

**Comment by enghch** [comment]
@lbnascimento I tried deleting that zero-byte log file but the error still occurs.

I also tried modifying the code to use a using statement like this:

```
            using (db = new LiteDatabase(Path))
            {

                // Get a collection (create it if it doesn't exist)
                ScenesCollection = db.GetCollection<Scene>(COLLECTION_SCENES);
                ScenesCollection.EnsureIndex(x => x.Name);
```

But still the same error happens.

**Comment by lbnascimento** [comment]
@enghch Does the error happen when you try to create an index on a collection that doesn't exist yet? If you remove that `EnsureIndex`, does everything else work correctly?

**Comment by enghch** [comment]
If I remove the EnsureIndex, things work until I make the first write to the DB .Then it fails the same way.

Interestingly, if I create a brand new database then EnsureInex actually works. But then it fails on the first write with the same error. "'Invalid Collection on 0. Full zero: True. Page Type: Empty. Prev/Next: 0/0. UniqueID: 58. ShareCounter: -1. '"

**Comment by mludlum** [comment]
I get the same error.  .NET Framework 4.7.2 Debug mode.   Happens on EnsureIndex.  My workaround is to try/catch the EnsureIndex.   But now I also get it when I Insert into the collection.

**Comment by ValonK** [comment]
We are experiencing the same Issue only on Release Mode x86 (**UWP**), the last working version is 4.1,4

LiteDB: 5.0.9

```
LiteDB.LiteException: Invalid Collection on 0. Full zero: True. Page Type: Empty. Prev/Next: 0/0. UniqueID: 4347. ShareCounter: -1. 
at LiteDB.Engine.CollectionPage..ctor(PageBuffer) + 0xca
at LiteDB.Engine.BasePage.ReadPage[T](PageBuffer) + 0xdd
at LiteDB.Engine.Snapshot.ReadPage[T](UInt32, FileOrigin&, Int64&, Int32&) + 0xd8
at LiteDB.Engine.Snapshot.GetPage[T](UInt32, FileOrigin&, Int64&, Int32&) + 0xb7
at LiteDB.Engine.CollectionService.Get(String, Boolean, CollectionPage&) + 0x4b
at LiteDB.Engine.Snapshot..ctor(LockMode, String, HeaderPage, UInt32, TransactionPages, LockService, WalIndexService, DiskReader, Boolean) + 0x11a
at LiteDB.Engine.TransactionService.<CreateSnapshot>g__create|42_0(TransactionService.<>c__DisplayClass42_0&) + 0x3e
at LiteDB.Engine.TransactionService.CreateSnapshot(LockMode, String, Boolean) + 0x8c8
at LiteDB.Engine.LiteEngine.<>c__DisplayClass30_0.<Upsert>b__0(TransactionService) + 0x23
at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2) + 0xa9
at LiteDB.Engine.LiteEngine.Upsert(String, IEnumerable`1, BsonAutoId) + 0x92
at LiteDB.LiteCollection`1.Upsert(BsonValue, T) + 0xa0
```

**Comment by JKamsker** [comment]
Consolidated into #2792, which combines this report with the related ones and tracks the fix. Closing this as a duplicate — please follow #2792, and comment there if your case is different.
