### ISSUE TITLE
[QUESTION] LiteDB usage from Parallel.ForEach causes LockRecursionException. How to handle?

### ISSUE THREAD

**Issue by eschlot** [litedb-org/LiteDB#1712]
I am doing write accesses to one collection within a Parallel.ForEach loop. In some cases this causes LockRecursionExceptions.

> System.Threading.LockRecursionException: Recursive read lock acquisitions not allowed in this mode.
>    at System.Threading.ReaderWriterLockSlim.TryEnterReadLockCore(TimeoutTracker timeout)
>    at LiteDB.Engine.LockService.EnterTransaction()
>    at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
>    at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
>    at LiteDB.LiteCollection`1.Update(T entity)
>    at ImageBrowser2.PictureDataSource.<>c__DisplayClass18_0.<DateScan>b__0(PictureData localPic)
> 

At the code position in the LiteDB I see that the corresponding lock is configured in such a way that this behavior is expected:

    private readonly ReaderWriterLockSlim _transaction = new ReaderWriterLockSlim(LockRecursionPolicy.NoRecursion);

At the moment I work around this problem by retrying:

    while (!success)
    {
        try
        {
            picturedata.Update(localPic);
            success = true;
        }
        catch (System.Threading.LockRecursionException ex)
        {
            Debug.WriteLine("LockRecursionException in DateScan on pic:" + localPic);
            Debug.WriteLine(ex);
        }
    }

                                 
I wonder if this is the intended way of handling this issue? I would prefer that LiteDB would handle this use-case internally by ensuring to retry in case the lock is currently used already. But maybe I misunderstand the error message. 

Any comment is very much appreciated.

**Comment by lbnascimento** [comment]
@eschlot I could not reproduce the issue. And I'm not sure why it's happening in the first place, given that LiteDB does not use recursive locks.

**Comment by eschlot** [comment]
The problem seem to be (at least from my investigation) that Parallel.ForEach somehow manages to call more than one method of LiteDB from one thread. And due to the fact that LiteDB is not expecting this (what is clear from the type of lock that is used in the LiteDB code) the exception happens and gets up to the user code. 

- maybe Windows is somehow using one thread at one point in time for more than one loop execution - I am no expert on this
- I am running async tasks (StorageFile access) as synchronous within the parallel.foreach loop and maybe this is a reason. 

The questions I have now are the following: 

- how does Windows reuse the thread? This is a question to the Windows parallel.foreach experts. 
- **Is it safe to simply retry in the seldom case that I get the exception? This is more or less the question to the LiteDB developers and why I asked here.** Is it save to assume that the state of the LiteDB is unchanged in case the call to `update` failed with the exception and is the `update `correctly performed if on the next try the exception does not get repeated?

**Comment by lbnascimento** [comment]
@eschlot I couldn't reproduce the issue so I can't test it, but I'm pretty sure it is safe to simply retry the operations that failed, due to write-ahead logging.

**Comment by RobinRSC** [comment]
We recently had a similiar issue with the `LockRecursionException` within a Asp.NET application that heavily utilizes the TAP pattern. It seems like the current LiteDB approach of preventing the same thread from accessing the database multiple times can cause issues with TAP pattern.
We investigated that the issue occurs when using LiteDB transaction or Enumerable together with the `await` keyword as the `await` keyword frees up the thread to execute some other task that is ready to be executed. If this other task also accesses the database, then the `LockRecursionException` is thrown.

The following code can cause issues in some scenarios:

```
db.BeginTrans();

var collection = db.GetCollection<Item>(Constants.CollectionName);
var item = await this.DoSomethingAsync();
collection.Insert(item.id, Item);

db.Commit();
```

and

```
var collection = db.GetCollection<Item>(Constants.CollectionName);
foreach (var item in db.FindAll())
{
    await this.ProcessAsync(item);
}
```

As both snippets use `await` the thread could execute some other task B. If task B also access the database, the exception is thrown. This scenario is hard to reproduce but occurs when the thread pool is highly utilized and different tasks access the db. I think this also the root cause of the exception thrown when using Parallel Foreach together with the LiteDB enumerator.

We can also confirm that the use of `ToList()` in the second code snippet can be used as workaround as it released the internal Read Lock.


Are there any plans to improve the current situation and add some proper TAP support?

**Comment by JKamsker** [comment]
Consolidated into #2790, which combines this report with the related ones and tracks the fix. Closing this as a duplicate — please follow #2790, and comment there if your case is different.
