### ISSUE TITLE
LiteDB can deadlock itself, it seems.

### ISSUE THREAD

**Issue by LennardF1989** [litedb-org/LiteDB#1863]
I'm not sure why, but LiteDB when used with IIS sometimes causes a deadlock issue:

```
System.ApplicationException: Object synchronization method was called from an unsynchronized block of code.
at System.Threading.Mutex.ReleaseMutex()
at LiteDB.SharedEngine.CloseDatabase()
at LiteDB.SharedDataReader.Dispose(Boolean disposing)
at LiteDB.SharedDataReader.Dispose()
at LiteDB.LiteQueryable`1.<ToDocuments>d__26.MoveNext()
at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
at LiteDB.LiteQueryable`1.Count()
```

We use a LiteDB connection in a Singleton using Shared-mode (we've used Direct before, but when IIS recycles it will not properly release the DB file), which is injected and constantly re-used. Whenever the above happens for whatever reason (seemingly when you try to do a lot of things with the LiteDB connection at once), any further call the the LiteDB connection will just never finish.

Has anyone seen this before? Is this something I can fix myself? Is it a bug? Am I misusing LiteDB? 

Using v5.0.7 right now, but can confirm it also happens with v5.0.9.

**Comment by decimvs** [comment]
I have experimented an issue similar: I'm using direct mode and a singleton instance, I have a timer that is polling cyclically at 5 ms a PLC for data. So there are many threads: timer events calls + main app. I'm polling for alarms, and, if I get a new alarm I save this in the alarms history in DB. If at the same time that a new alarm is registered (write op.) and user opens (read op.) the alarms history I'll get the same exception. I resolved this by adding a lock in the singleton get property to avoid access to LiteDB at same time.

**Comment by JKamsker** [comment]
Consolidated into #2787, which combines this report with the related ones and tracks the fix. Closing this as a duplicate — please follow #2787, and comment there if your case is different.
