### ISSUE TITLE
[cannot insert duplicate key in unique index '_id']

### ISSUE THREAD

**Issue by mukeshpiplai** [litedb-org/LiteDB#1891]
**Version**
LiteDB Studio (v1.0.2.0)

**Describe the bug**

Hi @mbdavid, I am facing the same issue in LiteDB Studio (v1.0.2.0). During opening a LiteDB database, it says Cannot Insert duplicate key in unique index '_id'. The duplicate value is '{"guide":961................ I want to shrink/reduce my LiteDB database generated in openbullet

**Code to Reproduce**

using GUI application of LiteDB Studio with upgrade v4 True option (Screenshot attached)
![mydb](https://user-images.githubusercontent.com/66024212/101183328-5e885a80-3675-11eb-86f1-2d61986496a7.png)

**Expected behavior**

I want to shrink/reduce database size with existing 335MB to possible lowest.

**Screenshots/Stacktrace**
![litedbIssue](https://user-images.githubusercontent.com/66024212/101183352-6b0cb300-3675-11eb-8ace-5042bdac8e9c.png)

**Additional context**

the database is attached herewith
[mydb.db](https://drive.google.com/file/d/1d7jl9_9WAFDK-Ao9Cft7r3ajzGA43uWO/view?usp=sharing)

**Comment by mukeshpiplai** [comment]
Erron in LiteDB.shell with db.shrink command

Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'LiteDB.IndexPage' to type 'LiteDB.DataPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.DataService.GetBlock(PageAddress blockAddress)
   at LiteDB.DataService.Read(PageAddress blockAddress)
   at LiteDB.QueryCursor.Fetch(TransactionService trans, DataService data, BsonReader bsonReader)
   at LiteDB.LiteEngine.<Find>d__9.MoveNext()
   at LiteDB.LinqExtensions.<Batch>d__0`1.MoveNext()
   at LiteDB.LiteEngine.InsertBulk(String collection, IEnumerable`1 docs, Int32 batchSize, BsonType autoId)
   at LiteDB.LiteEngine.Shrink(String password, IDiskService tempDisk)
   at LiteDB.Shell.Commands.Shrink.Execute(StringScanner s, Env env)
   at LiteDB.Shell.ShellProgram.Start(InputCommand input, Display display)
   at LiteDB.Shell.Program.Main(String[] args)

**Comment by JKamsker** [comment]
Consolidated into #2823, which combines this report with the related ones and tracks the fix. Closing this as a duplicate — please follow #2823, and comment there if your case is different.
