### ISSUE TITLE
Do LiteDB support for hosting the .db file in external disk?

### ISSUE THREAD

**Issue by yongshun950824** [litedb-org/LiteDB#1914]
I set up the LiteDB .db file to an (external disk) file share as this file will be read & write from multiple servers. But it hit **System.UnauthorizedAccessException: Access to the path is denied.** when inserting data.

Exception message:
```
System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.FlushOSBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at LiteDB.Engine.WalIndexService.CheckpointInternal()
   at LiteDB.Engine.WalIndexService.TryCheckpoint()
   at LiteDB.Engine.LiteEngine.Dispose(Boolean disposing)
   at LiteDB.SharedEngine.Dispose(Boolean disposing)
   at LiteDB.SharedEngine.Dispose()
   at LiteDB.LiteDatabase.Dispose(Boolean disposing)
   at LiteDB.LiteDatabase.Dispose()
```

So I checked the external file share and saw the file is created (with the -log file).

![image](https://user-images.githubusercontent.com/29250581/103961651-e50deb80-518f-11eb-8d5f-137065df36a2.png)

When I resubmit to insert data again. It prompts out **The process cannot access the file '\\file share path'\AuditLogDB.db' because it is being used by another process**

Exception message:
```
System.IO.IOException: The process cannot access the file '\\<file share path>\AuditLogDB.db' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at LiteDB.Engine.FileStreamFactory.GetStream(Boolean canWrite, Boolean sequencial)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at LiteDB.Engine.DiskService..ctor(EngineSettings settings, Int32[] memorySegmentSizes)
   at LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
   at LiteDB.SharedEngine.OpenDatabase()
   at LiteDB.SharedEngine.Pragma(String name)
```

So next, instead of a file share, I point the file path to the same drive as the IIS website folder, and it works correctly.

The attached code is the way I create LiteDatabase connection and use LiteRepository
       
```
 public Repository(Configuration configuration)
        {
            this._connectionString = LiteDBHelper.GetConnectionString(configuration);

            #region LiteDB configuration
            using (var db = new LiteDatabase(this._connectionString))
            {
                var isUtcDate = db.Pragma("UTC_DATE").AsBoolean;
                if (!isUtcDate)
                    db.Pragma("UTC_DATE", true);
            }
            #endregion

            this._liteRepository = new LiteRepository(this._connectionString);
        }
```

Environment:
Framework: .NET Framework 4.5.1
LiteDB version: 5.0.9 (latest)

Questions:
1. Is it possible to host the LiteDatabase file to an external disk (for file share)?
2. If yes, is it due to permission that made LiteDB unable to read/write the file?
3. Do I need to have code handling specialized for reading/writing from an external disk?

Thanks in advance for replying to my questions above.

**Comment by yongshun950824** [comment]
Found out the same issue with #1893

**Comment by JKamsker** [comment]
Consolidated into #2799, which combines this report with the related ones and tracks the fix. Closing this as a duplicate — please follow #2799, and comment there if your case is different.
