### ISSUE TITLE
[BUG] IOException on mutex when process left running for some time

### ISSUE THREAD

**Issue by tjmoore** [litedb-org/LiteDB#1918]
**Version**
LiteDB 5.0.9
.NET Core 3.1.403
CentOS 7.7 (note, platform in use has custom kernel)

**Describe the bug**
We have a service web API application that we're developing that runs on multiple platforms but over the holiday period our testers have found an issue when the service has been left running on linux (CentOS based system). When using the application there is a database call using shared mode and on opening the database it's throwing IOException on the global mutex.

**Code to Reproduce**
The application only opens the database during web requests. The process was left running for some time without the database being open or touching the database. Then the following code effectively would be called and this is where the exception is raised in the constructor on opening the database.

```
using (var db = new LiteDatabase("filename=database.db;Connection=shared;ReadOnly=true") { UtcDate = true })
{
    // do work
}
```

May attempt to produce a reproducable example that could be shared.

**Expected behavior**
No exception to be raised on the mutex when opening the database.

**Screenshots/Stacktrace**
```
System.IO.IOException: The system cannot open the device or file specified. : 'Global\\A4BC81403E0F366B89A06D796FC65AC91A2AEF11.Mutex'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at LiteDB.SharedEngine..ctor(EngineSettings settings)
   at LiteDB.ConnectionString.CreateEngine()
   at LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)
   at LiteDB.LiteDatabase..ctor(String connectionString, BsonMapper mapper)
```

**Additional context**
The web application uses IdentityServer4 to authenticate requests and we use LiteDB to implement a database for credentials. This error occured on authenticating first time after a period of days (a week or more) with the process constantly running and no database connection open.

The process is run under a systemd configured service. Restarting the service appeared to fix the problem.

**Comment by JKamsker** [comment]
The exception is thrown inside .NET's own `Mutex` constructor, before LiteDB touches the database ([call site](https://github.com/litedb-org/LiteDB/blob/47268cb4/LiteDB/Client/Shared/SharedMutexFactory.cs#L18-L21)). On Linux, .NET implements named mutexes with files under the temp directory (`/tmp/.dotnet/shm` and `/tmp/.dotnet/lockfiles`). If something deletes those while the process keeps running, later attempts to create a named mutex fail with exactly this `IOException` until the process restarts. On CentOS 7, systemd-tmpfiles cleans `/tmp` entries older than 10 days by default, and `tmpwatch` cron jobs are common too. That fits "a week or more of uptime, fixed by a restart".

What you can do:
- Exclude the folder from cleanup with a tmpfiles.d drop-in containing `x /tmp/.dotnet`, and check for tmpwatch jobs.
- Or, if this service is the only process using the file, use `Connection=direct` with one long-lived `LiteDatabase`. Direct mode doesn't use a named mutex.

If this doesn't cover your case, comment here and we'll reopen it.
