### ISSUE TITLE
[BUG] Deserialization of struct 'Index' causes an NullReferenceException

### ISSUE THREAD

**Issue by abremora** [litedb-org/LiteDB#1929]
**Version**
5.0.10

**Describe the bug**
Loading a document causes an NullReferenceException during deserialization if the document contains a property of type 'Index'.

**Code to Reproduce**
```csharp
using LiteDB;
using System;
using Xunit;

namespace LiteDb.Tests {
    public class LiteDbTest {
        [Fact]
        public void FindById_DeserializationWithIndexType_IsSuccessfull() {
            // Arrange
            using var db = new LiteDatabase(":memory:");

            var person = new Person {
                Name = "Alex"
            };

            var collection = db.GetCollection<Person>();
            collection.Insert(person);

            // Act

            // Next line causes:
            // System.NullReferenceException : Object reference not set to an instance of an object.
            //Stack Trace: 
            //  lambda_method(Closure, BsonDocument)
            //  BsonMapper.Deserialize(Type type, BsonValue value)
            //  BsonMapper.DeserializeObject(EntityMapper entity, Object obj, BsonDocument value)
            //  BsonMapper.Deserialize(Type type, BsonValue value)
            //  LiteQueryable`1.< ToEnumerable > b__27_2(BsonDocument x)
            //  SelectEnumerableIterator`2.MoveNext()
            //  Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean & found)
            //  Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
            //  LiteCollection`1.FindById(BsonValue id)
            //  UnitTest1.Deserialization_Index_IsSuccessfull() line 21
            var result = collection.FindById(person.Id);

            // Assert
            Assert.Equal(result.Name, person.Name);
        }
    }

    public class Person {
        public string Id { get; set; } = Guid.NewGuid().ToString();
        public string Name { get; set; }
        public Index Selection { get; set; }  // <- Causes the exception
    }
}
```

**Expected behavior**
The struct 'Index' can be deserialized.
See: https://docs.microsoft.com/en-us/dotnet/api/system.index?view=net-5.0

**Screenshots/Stacktrace**
```
Result StackTrace:	
at lambda_method(Closure , BsonDocument )
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.DeserializeObject(EntityMapper entity, Object obj, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.LiteQueryable`1.<ToEnumerable>b__27_2(BsonDocument x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at LiteDB.LiteCollection`1.FindById(BsonValue id)
   at LiteDb.Tests.LiteDbTest.FindById_DeserializationWithIndexType_IsSuccessfull() in C:\dev\LiteDb.Tests\LiteDb.Tests\LiteDbTest.cs:line 34
Result Message:	System.NullReferenceException : Object reference not set to an instance of an object.
```

**Additional context**
Test environment
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiteDB" Version="5.0.10" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.8.3" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>

```

**Comment by JKamsker** [comment]
Fixed in #2759 — thanks for the ready-to-run xUnit repro, @abremora, that made this easy to pin down. `System.Index` values now deserialize properly instead of NREing in the generated mapper. Apologies for the long wait.
