### ISSUE TITLE
[BUG] Upgrading database give : Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by alb3ric** [litedb-org/LiteDB#1949]
**Version**
5.0.10 .NET 4.7 Windows 2016

**Describe the bug**

I have a database in version 4.1.4. When I try to upgrade it i get the following message :

System.NullReferenceException: Object reference not set to an instance of an object.
   at LiteDB.Engine.FileReaderV7.<GetDocuments>d__8.MoveNext()
   at LiteDB.Engine.LiteEngine.RebuildContent(IFileReader reader)
   at LiteDB.Engine.LiteEngine.Upgrade(String filename, String password, Collation collation)
   at LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)

**Code to Reproduce**

I can send the database (38MO)

**Screenshots/Stacktrace**

System.NullReferenceException: Object reference not set to an instance of an object.
   at LiteDB.Engine.FileReaderV7.<GetDocuments>d__8.MoveNext()
   at LiteDB.Engine.LiteEngine.RebuildContent(IFileReader reader)
   at LiteDB.Engine.LiteEngine.Upgrade(String filename, String password, Collation collation)
   at LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)

Any clue ? :)

Thanks in advance for your help, I'm migrating to v5.0 and I don't want all my users to lose there database.

Regards

**Comment by lbnascimento** [comment]
@alb3ric Please send the datafile to lbnascimento@inf.ufrgs.br

**Comment by JKamsker** [comment]
Consolidated into #2826, which combines this report with the related ones and tracks the fix. Closing this as a duplicate — please follow #2826, and comment there if your case is different.
