### ISSUE TITLE
[BUG] LiteDB ENSURE: stored slot must be same as called

### ISSUE THREAD

**Issue by alb3ric** [litedb-org/LiteDB#1984]
Version
5.0.10 .NET 4.7 Windows 2016

Describe the bug

I have a database in version 5.0.10. When upserting I got this error => "LiteDB ENSURE: stored slot must be same as called"
and then it keet doing it 
If I reopen the database i got this error : LiteDB ENSURE: invalid segment position and then when inserting the previous errors is coming back.

Code to Reproduce

I can send the database (73MO)

Screenshots/Stacktrace

System.Exception: LiteDB ENSURE: stored slot must be same as called
   at LiteDB.Constants.ENSURE(Boolean conditional, String message)
   at LiteDB.Engine.Snapshot.GetFreeDataPage(Int32 bytesLength)
   at LiteDB.Engine.DataService.<>c__DisplayClass3_0.<<Insert>g__source|0>d.MoveNext()
   at LiteDB.Engine.BufferWriter..ctor(IEnumerable`1 source)
   at LiteDB.Engine.DataService.Insert(BsonDocument doc)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass31_0.<Upsert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Upsert(T entity)

Thanks in advance for the help.

Regards

**Comment by mbdavid** [comment]
Hi @alb3ric, this ensure prevent database to be corrupted. I add this checkes to capture corruption problems... 

Can you send me your database (have any sensitive/customer data)? You can send to `mauricio.david` at gmail.

**Comment by alb3ric** [comment]
Hello Mauricio,

I understand that the checks is to capture corruption problems and I think it's great.
I just don't understand why I get this error :)

I just sent you the file by email.

Thanks in advance.

Regards

**Comment by honorew** [comment]
Is there a solution? Me too

**Comment by BenWoodford** [comment]
I too would like to know how to avoid/solve this issue...

**Comment by BenWoodford** [comment]
FYI for all: I managed to make a system for detecting this and repairing the DB by running .Rebuild() which failed due to trying to insert a duplicate ID, so I catch the exception, get all the data out of the DB by just using FindAll, and then create a new one fresh and insert the data into that one, then for the sake of cleanliness my application closes and re-opens to ensure a clean slate.

**Comment by zhoushinian** [comment]
any solutions? how to avoid/solve it?

**Comment by JKamsker** [comment]
This ENSURE fires when a collection's free-page list points at a page with a different slot, so it detects corruption that already happened; we haven't found the cause and have no repro. Since 5.0.10, a related free-page race was fixed (5.0.21), and the current prerelease can rebuild a file flagged this way on open with `AutoRebuild=true`.

For anyone hitting this, it would help to know:
- your LiteDB version, and whether it still happens on 5.0.21+ or the latest prerelease (`dotnet add package LiteDB --prerelease`)
- the connection string (Direct or Shared) and whether several instances, processes or threads write to the file
- whether the process was killed or the disk filled up before the first error
- the `.db` and `-log.db` files, if they can be shared

**Comment by JKamsker** [comment]
We reproduced this with a database we built ourselves: three collections, each with one thread upserting documents of changing size and one thread deleting ranges. On 5.0.10 it throws `LiteDB ENSURE: stored slot must be same as called` from `Upsert`, and after reopening, `ENSURE: invalid segment position`, the same sequence as in this report. The cause is a race on the shared free-page list when different collections are written at the same time, so one page ends up used twice. The same program ran for three minutes on the current version without errors. Files already damaged by older versions need `Rebuild()` or an export into a new database; that is tracked in #2825.

You can try the latest prerelease with `dotnet add package LiteDB --prerelease`. If it still happens on the prerelease, comment here with the details and we'll reopen it.
