### ISSUE TITLE
[BUG] ENSURE: share counter must be > 0 in Release()

### ISSUE THREAD

**Issue by plainionist** [litedb-org/LiteDB#2003]
**Version**
5.0.10/.net FW 4.8/Windows 10 1909

**Describe the bug**
Sporadically i get the following exception:

LiteDB ENSURE: share counter must be > 0 in Release()
   at LiteDB.Constants.ENSURE(Boolean conditional, String message)
   at LiteDB.Engine.TransactionService.Dispose()
   at LiteDB.Engine.TransactionMonitor.ReleaseTransaction(TransactionService transaction)
   at LiteDB.Engine.QueryExecutor.<>c__DisplayClass10_0.<<ExecuteQuery>g__RunQuery|0>d.<>m__Finally1()
   at LiteDB.Engine.QueryExecutor.<>c__DisplayClass10_0.<<ExecuteQuery>g__RunQuery|0>d.MoveNext()
   at LiteDB.BsonDataReader.Read()
   at LiteDB.LiteQueryable`1.<ToDocuments>d__26.MoveNext()

There might run multiple read operations and optional single write operation in parallel.
the DB is only used by a single process and is created from a simple file (no additional connectionString options).

**Code to Reproduce**
not available as sporadically happens with different queries

**Expected behavior**
no exception should be thrown 

I know it is difficult to hunt such type of issues - any hints how we could figure out the root cause? is this related to multi-threading?

**Comment by JKamsker** [comment]
Consolidated into #2817, which combines this report with the related ones and tracks the fix. Closing this as a duplicate — please follow #2817, and comment there if your case is different.
