### ISSUE TITLE
[BUG] "Access denied to Globall\\###.Mutex" when opening a shared connection to database in UWP application

### ISSUE THREAD

**Issue by ruhoch** [litedb-org/LiteDB#2009]
**Version**
LiteDb: 5.0.10
Win 10,
.NET Standard 2.0
UAP target = 10.0.18362.0
UAP min target = 10.0.17763.0

**Describe the bug**
I need to establish a shared connection to a database in a UWP application because I also need a background task in another process to access it. However when I attempt to create the LiteDatabase object with a shared connection, an Access Violation Exception is thrown 100% of the time. At this time the UWP app is the only process attempting to access the database. 

When I switch to a direct connection I am able to create a database object without issue, but obviously this solution does not work across process boundaries.

**Code to Reproduce**
> public ILiteDatabase GetDatabase()
> {
>     lock (SyncRoot)
>     {
>         if (liteDatabase != null)
>         {
>             return liteDatabase;
>         }
>          var bsonMapper = new BsonMapper();
> 
>         // register how to serialize/deserialize DeviceConfiguration.
>         bsonMapper.RegisterType(
>                 serialize: o => o.ToByteArray(),
>                 deserialize: bson => DeviceConfiguration2.Parser.ParseFrom(bson.AsBinary));
> 
>         // register how to serialize/deserialize AssetInfo.
>         bsonMapper.RegisterType(
>                 serialize: o => o.ToByteArray(),
>                 deserialize: bson => AssetInfo.Parser.ParseFrom(bson.AsBinary));
> 
>         // specify the _id in LiteDB.
>         bsonMapper.Entity<DeviceConfigurationCache>().Id(x => x.Index);
>         ConnectionString connection = new ConnectionString(this.connectionString)
>         {
>             Connection = ConnectionType.Shared,
>         };
> 
>         liteDatabase = new LiteDatabase(this.connectionString, bsonMapper); // <-- Access Denied exception caught here
>         return liteDatabase;
>     }
> }

**Expected behavior**
A new LiteDatabase object with a shared connection should be created and returned.

**Screenshots/Stacktrace**
Exception message:
Access to the path 'Global\7191D9E47B881DDEBB412BB6C28A92C41BB64853.Mutex' is denied.

Stack:
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at LiteDB.SharedEngine..ctor(EngineSettings settings)
   at LiteDB.ConnectionString.CreateEngine()
   at LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)
   at Boxer.LiteDbProvider.GetDatabase() in C:\CE\Unify\Boxer\uwp\src\Boxer\Services\LiteDbProvider.cs:line 73

**Comment by mosunchao** [comment]
this is caused by the SharedEngine initializing a named Mutex using "Global\\".  I cloned this repo and removed "Global\\", and this works in UWP and BackgroundTask sharing the same DB.

**Comment by joergwork** [comment]
+1
(Almost) the same here ...

**Comment by mikea314** [comment]
Doing this fixed the issue for me, but not sure if it's something you could build into the Nuget Package ?
Requires the following Nugets:
 - System.Security.Principal.Windows
 - System.Threading.AccessControl

#if NETFRAMEWORK
......  no changes ....
#else

                if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                {
                    var allowEveryoneRule = new MutexAccessRule(new SecurityIdentifier(WellKnownSidType.WorldSid, null),
                         MutexRights.FullControl, AccessControlType.Allow);

                    var securitySettings = new MutexSecurity();
                    securitySettings.AddAccessRule(allowEveryoneRule);

                    _mutex = new Mutex(false, "Global\\" + name + ".Mutex", out _);
                    _mutex.SetAccessControl(securitySettings);
                }
                else
                {
                    _mutex = new Mutex(false, "Global\\" + name + ".Mutex");
                }

#endif

**Comment by mosunchao** [comment]
> Doing this fixed the issue for me, but not sure if it's something you could build into the Nuget Package ? Requires the following Nugets:
> 
> * System.Security.Principal.Windows
> * System.Threading.AccessControl
> 
> #if NETFRAMEWORK ...... no changes .... #else
> 
> ```
>             if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
>             {
>                 var allowEveryoneRule = new MutexAccessRule(new SecurityIdentifier(WellKnownSidType.WorldSid, null),
>                      MutexRights.FullControl, AccessControlType.Allow);
> 
>                 var securitySettings = new MutexSecurity();
>                 securitySettings.AddAccessRule(allowEveryoneRule);
> 
>                 _mutex = new Mutex(false, "Global\\" + name + ".Mutex", out _);
>                 _mutex.SetAccessControl(securitySettings);
>             }
>             else
>             {
>                 _mutex = new Mutex(false, "Global\\" + name + ".Mutex");
>             }
> ```
> 
> #endif

if you intend to share the mutex between UWP foreground app and background task, I think simply removing "Global\\" is the simplest fix without additional dependencies.

if you are trying to create a mutex in UWP and synchronized with a different process outside the UWP app container, then yeah..the above fix is quite interesting...

**Comment by JKamsker** [comment]
Consolidated into #2793, which combines this report with the related ones and tracks the fix. Closing this as a duplicate — please follow #2793, and comment there if your case is different.
