### ISSUE TITLE
[BUG] The read lock is being released without being held

### ISSUE THREAD

**Issue by laurentiucocanu** [litedb-org/LiteDB#2017]
**Version**
5.0.10/Windows 10/NET 5

**Describe the bug**
Trying to read and update records in a parallel foreach throws an exception with the following message: "The read lock is being released without being held."
It seems to run fine in 5.0.3, but not in 5.0.10.

**Code to Reproduce**
        
        public class Target
        {
            [BsonId]
            public ObjectId Id { get; set; }

            public string Name { get; set; }

            public DateTime LastUpdateCheck { get; set; }
        }

        [Fact]
        public void InsertReadTest()
        {
            var dbFullPath = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
            try
            {
                using (var db = new LiteDatabase(dbFullPath))
                {
                    var table = db.GetCollection<Target>("targets");
                    for (int i = 0; i < 10000; i++)
                    {
                        table.Insert(new Target
                        {
                            Name = $"Name_{i}",
                            LastUpdateCheck = DateTime.UtcNow
                        });
                    }
                    var targetIds = table.FindAll().Select(t => t.Id);
                    Parallel.ForEach(targetIds, targetId =>
                    {
                        var target = table.FindOne(ur => ur.Id == targetId);
                        target.LastUpdateCheck = DateTime.UtcNow;
                        table.Update(target);
                    });
                }
            }
            finally
            {
                File.Delete(dbFullPath);
            }
        }

**Expected behavior**
No exception thrown.

**Screenshots/Stacktrace**
The read lock is being released without being held.

   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)

Inner exception:
      at System.Threading.ReaderWriterLockSlim.ExitReadLock()
   at LiteDB.Engine.TransactionMonitor.ReleaseTransaction(TransactionService transaction)
   at LiteDB.Engine.QueryExecutor.<>c__DisplayClass10_0.<<ExecuteQuery>g__RunQuery|0>d.MoveNext()
   at LiteDB.BsonDataReader.Read()
   at LiteDB.LiteQueryable`1.<ToDocuments>d__26.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable`1.InternalPartitionEnumerable.GrabChunk_Buffered(KeyValuePair`2[] destArray, Int32 requestedChunkSize, Int32& actualNumElementsGrabbed)
   at System.Collections.Concurrent.Partitioner.DynamicPartitionEnumerator_Abstract`2.MoveNext()
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()

**Comment by Rickedb** [comment]
Any updates? Facing the same bug when using Tasks

**Comment by gorillapower** [comment]
Im also getting these on .NET 6.0

**Comment by ysinsane** [comment]
Me too

**Comment by tdsalty** [comment]
Also getting on .NET 6 - using singleton and no transactions whatsoever.  Are there implicit transactions?

**Comment by ultravelocity** [comment]
Sadly still getting the same issue in .NET 6

**Comment by IbrahimElshafey** [comment]
I getting the same error today at 13-07-2023
My code:
```C#
 public void AddFailedRequest(FailedRequest failedRequest)
        {
            using (var db = new LiteDatabase(Constants.FailedRequestsDb))
            {
                var failedRequests = db.GetCollection<FailedRequest>(Constants.FailedRequestsCollection);
                failedRequest.Created = DateTime.Now;
                failedRequests.Insert(failedRequest);
                //db.Commit();
            }
        }
```

``` C#
public void HandleFailedRequestes()
        {
            _ = CallFailedRequests();
            async Task CallFailedRequests()
            {
                try
                {
                    _logger.LogInformation("Start handling failed requests.");
                    using (var db = new LiteDatabase(Constants.FailedRequestsDb))
                    {
                        var failedRequests = db.GetCollection<FailedRequest>(Constants.FailedRequestsCollection);
                        foreach (var request in failedRequests.FindAll())
                        {
                            _logger.LogInformation($"Found `{failedRequests.Count()}` failed request.");
                            try
                            {
                                var client = _httpClientFactory.CreateClient();
                                var response = await client.PostAsync(
                                    request.ActionUrl,
                                    new ByteArrayContent(request.Body));
                                response.EnsureSuccessStatusCode();
                                var result = await response.Content.ReadAsStringAsync();
                                if (!(result == "1" || result == "-1"))
                                    throw new Exception("Expected result must be 1 or -1");
                                failedRequests.Delete(request.Id);
                            }
                            catch (Exception)
                            {
                                request.AttemptsCount++;
                                _logger.LogInformation(
                                    $"Request `{request.Id}` failed againg for `{request.AttemptsCount}` times");
                                request.LastAttemptDate = DateTime.Now;
                                failedRequests.Update(request);
                                throw;
                            }
                        }
                    }
                    _logger.LogInformation("End handling failed requests.");
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Error when handling failed requests.");
                }
                finally
                {
                    await Task.Delay(_settings.CheckFailedRequestEvery);
                    await CallFailedRequests();
                }
            }
        }
```

**Comment by JKamsker** [comment]
Consolidated into #2790, which combines this report with the related ones and tracks the fix. Closing this as a duplicate — please follow #2790, and comment there if your case is different.
