### ISSUE TITLE
[BUG] Cannot insert duplicate key in unique index '_id'

### ISSUE THREAD

**Issue by meeety** [litedb-org/LiteDB#2043]
**Version**
5.0.8

**Describe the bug**
My database uses table "records" configured with AutoId. The database table contains documents with IDs bigger than stored within the Page/Node thus  the exception "Cannot insert duplicate key in unique index '_id'" is thrown while inserting new document. It is not possible to insert new documents from now on.

**Code to Reproduce**
I can't enclose the corrupted database due to size ~50MB. But I can send it to you via wetransfer for example. It is not easy to reproduce the issue, but it happened probably while intensive writing & reading operations at the same time from multiple threads. We also use Rebuild but not sure whether it was running at the same time.

**Expected behavior**
The database should not never end up corrupted. It should be possible to insert new documents if auto-id is enabled for the table.

**Logged exception**
```
LiteDB.LiteException: Cannot insert duplicate key in unique index '_id'. The duplicate value is '{"$numberLong":"31156"}'.
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte level, IndexNode last)
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, IndexNode last)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Insert(IEnumerable`1 entities)
```

**Comment by lbnascimento** [comment]
@meeety Please send the datafile to lbnascimento@inf.ufrgs.br

**Comment by meeety** [comment]
@lbnascimento Thank you, I have sent it. Regards, Vlastimil

**Comment by lbnascimento** [comment]
@meeety Something happened, I did not get your email.

**Comment by meeety** [comment]
WeTransfer service notified me you successfully downloaded the file so hopefully everything is all right now.

**Comment by lbnascimento** [comment]
@meeety There was some sort of corruption in an index. Luckily, all data is still there. We're investigating the issue, and I can send you a fixed datafile that you can keep using in the meantime.

**Comment by lbnascimento** [comment]
@meeety Could you provide some pieces of code from your application? I want to know how you're opening and using the database. Also, do you have any idea how many threads are usually accessing the datafile at the same time?

**Comment by meeety** [comment]
@lbnascimento Thank you for investigation. I don't need the repaired database since this issue can occur on customer side and finally we will not be able to fix it like that. 
I have checked the usage of LiteDB:
* we have 2 LiteDatabase instances (opened for different data file)
** First one uses FileStorage only (A)
** Second one uses the database I sent you  (B)
* The (B) writes data in one thread (Background thread) using the ILiteCollection.Insert(IEnumerable<T> entities)
* The (B) stores huge data and we need to maintain the database size so we need to remove old data sometime. This is done in Timer's callback (so in ThreadPool thread) 
** we use ILiteCollection.Find(Expression<Func<T, bool>> predicate, int skip = 0, int limit = int.MaxValue) to find data to be deleted
** we use ILiteCollection.Count() to get total number of documents
** we also use ILiteCollection.Query().OrderByDescending().Skip().Limit(),ToList(); to get ordered data based on specified criteria
** all the above is running in transaction (BeginTransaction(), CommitTransaction())
* There can also occur user interaction when trying to retrieve data from database and show in UI
** It runs in ThreadPool long running task
** we also use ILiteCollection.Query().OrderByDescending().Skip().Limit(),ToList(); to get ordered data based on user specified criteria

Hopefully it will help and navigate you the right direction. Unfortunately the code itself is quite big to share with you. If you need something else, I will try to help...

**Comment by carefree525** [comment]
> @meeety There was some sort of corruption in an index. Luckily, all data is still there. We're investigating the issue, and I can send you a fixed datafile that you can keep using in the meantime.

My data file has the same error, I would like to know how to fix it?

**Comment by JKamsker** [comment]
Thanks for the details on your threading setup. We ran that pattern on the current version for 20 seconds (one writer inserting batches, a transactional cleanup doing Count/ordered Query/Delete, several readers running ordered queries). There was no duplicate-key error and the next auto-id was always correct. Several concurrency fixes have shipped since 5.0.8. To reproduce it we'd need:

- whether it still happens on 5.0.21 or the latest prerelease (`dotnet add package LiteDB --prerelease`)
- whether `Rebuild()` can run while other threads use the same `LiteDatabase` (our test didn't cover that)
- from anyone seeing this now: the LiteDB version, connection string, and the data file if it's shareable

As a workaround, `db.Rebuild()` recreates the indexes from the stored data.

The issue stays open, and we'll also try to reproduce it on our side.

**Update:** We built our own databases to try to recreate this, on 5.0.8 and on the current version. We ran your pattern: one thread inserting batches with auto-id, a timer running a transaction with `Count`, an ordered query and `Delete`, and several readers. We also ran it on an 87 MB file with 100k documents, with `Rebuild()` running every two seconds on another thread, and separately while killing the process mid-write 40 times. The `_id` index stayed consistent and the next auto-id was always max + 1, so we couldn't reproduce it yet. What would help most is an affected database (`.db` plus `-log.db`, zipped), or from anyone seeing this now, the LiteDB version and whether `Rebuild()` can run while other threads use the database. The issue stays open.
