### ISSUE TITLE
nuget upgrade from 4.1.4 to 5.0.11 fails

### ISSUE THREAD

**Issue by ajweber** [litedb-org/LiteDB#2055]
Targeting .Net 4.6.2, when I try to use the NuGet Package Manager in VS2015, the new version appears to download to the local packages folder, but during upgrade/install to my project it fails, rolls-back and requires a VS restart to recover.  The following is what I pulled from the package manager output window:

`System.ArgumentException: The array must contain at least one element.
Parameter name: items
   at Microsoft.TeamFoundation.Common.TFCommonUtil.CheckArrayForNullOrEmpty[T](T[] array, String arrayName)
   at Microsoft.TeamFoundation.VersionControl.Client.Workspace.GetPendingChanges(String[] items, RecursionType recursion, Boolean includeDownloadInfo)
   at NuGet.TeamFoundationServer.DefaultTFSSourceControlManager.PendDeleteFiles(IEnumerable`1 fullPaths, String root, INuGetProjectContext nuGetProjectContext)
   at NuGet.ProjectManagement.FileSystemUtility.DeleteFile(String fullPath, INuGetProjectContext nuGetProjectContext)
   at NuGet.ProjectManagement.FolderNuGetProject.DeletePackage(PackageIdentity packageIdentity, INuGetProjectContext nuGetProjectContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.<DeletePackage>d__75.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__6.MoveNext()`

**Comment by JKamsker** [comment]
The stack trace is entirely inside Visual Studio 2015's NuGet/TFS integration. While NuGet deletes the old `LiteDB.4.1.4` package folder, `DefaultTFSSourceControlManager.PendDeleteFiles` calls `Workspace.GetPendingChanges` with an empty list and TFS rejects it. That happens before any LiteDB 5 file is used, so there's nothing in the package that could avoid it. It usually shows up when the `packages` folder isn't under source control or its files are already missing.

Workarounds:
- Unbind the solution from TFS, or delete `packages\LiteDB.4.1.4` by hand, then install 5.x.
- Or use a newer Visual Studio/NuGet client, or move the project to `PackageReference`.

Also note that 4.x → 5.x is a breaking upgrade. The API changed, and existing v4 data files have to be converted by opening them once with `Upgrade=true` in the connection string.

If this doesn't cover your case, comment here and we'll reopen it.
