### ISSUE TITLE
[BUG]: LiteDB ENSURE: current value must fit inside defined buffer

### ISSUE THREAD

**Issue by Stitch10925** [litedb-org/LiteDB#2062]
**Version**
.NET Core 3.1 - Package version 5.0.11 - Development on Windows (Visual Studio) - Compiled for Linux x64

- Development: Windows 10 x64 - PRO
- Deployment: Ubuntu 21.04 (headless) x64 (in a Linux Container)

**Describe the bug**
When updating data into the database on Linux I get a buffer exception. Doing exactly the same, with the same code on Windows works without issue. Error occurs during Update (item per item or as bulk) as well as when using Upsert.

**Code to Reproduce**

`public int Update<T>(IEnumerable<T> itemsToUpdate) where T : DbBase
{
	if (itemsToUpdate == null || !itemsToUpdate.Any()) 
	{ 
		return 0; 
	}

	using (var db = new LiteDatabase(_databaseName))
	{
		//return db.GetCollection<T>().Update(itemsToUpdate);

		foreach(var item in itemsToUpdate)
		{
			_logger.LogDebug("Updating item: {@item}", item);
			db.GetCollection<T>().Update(item);
		}

		return 0;
	}
}

public bool UpdateOrInsert<T>(T entity) where T : DbBase
{
	using (var db = new LiteDatabase(_databaseName))
	{
		return db.GetCollection<T>().Upsert(entity._Id, entity);
	}
}`

**Expected behavior**
I would expect the database to save the update on Linux like it does on Windows.

**Screenshots/Stacktrace**

[16:33:20 DBG] Updating item: {"Title": "Pamper Maat", "Explanation": null, "Values": [{"Value": "P2", "Date": "2021-06-30T00:00:00.0000000+00:00", "$type": "DbValue"}, {"Value": "P1", "Date": "2021-07-27T00:00:00.0000000+00:00", "$type": "DbValue"}], "Enabled": true, "_Id": {"Timestamp": 1629702508, "Machine": 7735715, "Pid": 2316, "Increment": 14070575, "CreationTime": "2021-08-23T07:08:28.0000000Z", "$type": "ObjectId"}, "$type": "DbStatistic"}
System.Exception: LiteDB ENSURE: current value must fit inside defined buffer
   at LiteDB.Constants.ENSURE(Boolean conditional, String message)
   at LiteDB.Engine.BufferWriter.Write(Byte[] buffer, Int32 offset, Int32 count)
   at LiteDB.Engine.BufferWriter.WriteCString(String value)
   at LiteDB.Engine.BufferWriter.WriteElement(String key, BsonValue value)
   at LiteDB.Engine.BufferWriter.WriteDocument(BsonDocument value, Boolean recalc)
   at LiteDB.Engine.DataService.Update(CollectionPage col, PageAddress blockAddress, BsonDocument doc)
   at LiteDB.Engine.LiteEngine.UpdateDocument(Snapshot snapshot, CollectionPage col, BsonDocument doc, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass27_0.<Update>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Update(String collection, IEnumerable`1 docs)
   at LiteDB.LiteCollection`1.Update(T entity)

**Comment by Stitch10925** [comment]
Update:

I decided to run the application on IIS instead of Linux because of the issue described above. However, when running the application in IIS I get the exact same error.

What is even more odd, is that when I attach Visual Studio to the IIS process to debug the issue, the problem does not occur anymore. Once I detach the remote debugging the issue is back.

Very odd.

**Comment by Stitch10925** [comment]
Update 2:

By downloading the source code, adding it to my solution and stepping through, I finally managed to figure out what the problem was... and it's kind of stupid.

I have a base class that holds the ID field, which was defined as follows:

`internal class DbBase
{
	public ObjectId _Id { get; set; }
}`

When Updating or Upserting the object it would internally generate the following BSON Document (which seems to be incorrectly formatted);

`{
	{
		"_id": 
		{
			"$oid":"6137369eca849612d53b8e27"
		},
		"Title": "Pamper Maat",
		"Values":[
			{
				"Value":"P2",
				"Date":
				{
					"$date":"2021-06-29T22:00:00.0000000Z"
				}
			},
			{
				"Value":"P1",
				"Date":
				{
					"$date":"2021-07-26T22:00:00.0000000Z"
				}
			}
		],
		"Enabled":true"_Id":
		{
			"$oid":"6137369eca849612d53b8e27"
		}
	}
}`

Note the weird "_Id" addition at the end of the BSON;

After changing my base class to the following (i.e.: making the variable name all lowercase):

`internal class DbBase
{
	public ObjectId _id { get; set; }
}`

It now generates a correctly formatted BSON document and saving works:

`{
	{
		"_id":
		{
			"$oid":"6137589239b8dd0bcca32573"
		},
		"Title":"Pamper Maat",
		"Values":
		[
			{
				"Value":"P2",
				"Date":
				{
					"$date":"2021-06-29T22:00:00.0000000Z"
				}
			}
			,
			{
				"Value":"P1",
				"Date":
				{
					"$date":"2021-07-26T22:00:00.0000000Z"
				}
			}
		],
		"Enabled":true
	}
}`

I hope this is something that can be looked at/fixed in a future release. Retrieving the documents using an "_Id" field (with uppercase "I") seems to work just fine, but updating doesn't seem to like it too much.
