### ISSUE TITLE
Method not found: 'Void System.Threading.Mutex..ctor on NET5.0 target framework.

### ISSUE THREAD

**Issue by thanhy** [litedb-org/LiteDB#2079]
We're seeing below runtime exception for an executable building with NET5.0 target framework referencing LiteDB 5.0.11 nuget package.   Does LiteDB support NET5.0 target framework?

System.MissingMethodException: Method not found: 'Void System.Threading.Mutex..ctor(Boolean, System.String, Boolean ByRef, System.Security.AccessControl.MutexSecurity)'.
at LiteDB.SharedEngine..ctor(EngineSettings settings)
at LiteDB.ConnectionString.CreateEngine()
at LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)
at LiteDB.LiteDatabase..ctor(String connectionString, BsonMapper mapper)

**Comment by stigzler** [comment]
Shame he/they can't be arsed to comment really, isn't it?

**Comment by nh43de** [comment]
> Shame he/they can't be arsed to comment really, isn't it?

.net 5 is EOL and use cases for LiteDb are diminishing

**Comment by JKamsker** [comment]
This is fixed on the `dev` branch. `dev` ships as the LiteDB 6.x prereleases.

Please try the latest prerelease (currently **6.0.0-prerelease.81**):

```
dotnet add package LiteDB --prerelease
```

If the problem still happens on the prerelease, comment here with the version you used and a repro, and we'll reopen the issue.
