### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cmalpass** [litedb-org/LiteDB#2108]
**Version**
5.0.10

**Describe the bug**
Concurrent operations each insert progress of the operation as it progresses from creation through to completion or error as records into the litedb database. This is used as part of an upload queue. At some point in the processing of the queue the exception throws. It is not consistent. For some users this is causing the exception "there is not enough space on the disk". The users are able to delete the data-log.db file and future operations are successful.

This makes it seem like the transactions are not getting applied as expected to the db and there is a corruption of some kind either as a result or as the cause of this issue.

**Code to Reproduce**
```
  var collection = db.GetCollection<FileOperationResult>("fileOperationResult");
  collection.Insert(item);
```

**Expected behavior**
Expects to be able to insert the record into the litedb without issue or exception.

**Screenshots/Stacktrace**
ERROR - There is not enough space on the disk.

System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.Security.Cryptography.CryptoStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at LiteDB.Engine.AesStream.Write(Byte[] array, Int32 offset, Int32 count)
   at LiteDB.Engine.DiskService.Write(IEnumerable`1 pages, FileOrigin origin)
   at LiteDB.Engine.WalIndexService.CheckpointInternal()
   at LiteDB.Engine.WalIndexService.TryCheckpoint()
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Insert(T entity)

**Additional context**
This is happening as a follow-on process that is part of a concurrent operation on a queue. Perhaps if the database is corrupted due to not being disposed of properly there is another cause unrelated to this but unsure as of yet. Other operations attempting to interact with the database also result in the "not enough space" exception once this behavior is triggered.

**Comment by JKamsker** [comment]
Consolidated into #2821, which combines this report with the related ones and tracks the fix. Closing this as a duplicate — please follow #2821, and comment there if your case is different.
