### ISSUE TITLE
OutOfMemoryException at System.Linq.Enumerable.ToArray

### ISSUE THREAD

**Issue by mawi77** [litedb-org/LiteDB#2139]
Hi

I am using version 5.0.11.0 and have a collection of Task objects named Task and make calls like this:

        Using db As New LiteDB.LiteDatabase(String.Format("Filename={0};connection=shared", DBLiteName))
            GetTasksCollection = db.GetCollection(Of Task)("Task").Find(Function(t) (t.enabled And Not t.name.StartsWith("ServiceChecker"))).ToArray
        End Using

After my application is running for 1 or 2 weeks this starts to fail

System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at LiteDB.Engine.MemoryCache.Extend()
   at LiteDB.Engine.MemoryCache.GetFreePage()
   at LiteDB.Engine.MemoryCache.<>c__DisplayClass5_0.<GetReadablePage>b__0(Int64 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at LiteDB.Engine.MemoryCache.GetReadablePage(Int64 position, FileOrigin origin, Action`2 factory)
   at LiteDB.Engine.DiskReader.ReadPage(Int64 position, Boolean writable, FileOrigin origin)
   at LiteDB.Engine.Snapshot.ReadPage[T](UInt32 pageID, FileOrigin& origin, Int64& position, Int32& walVersion)
   at LiteDB.Engine.Snapshot.GetPage[T](UInt32 pageID, FileOrigin& origin, Int64& position, Int32& walVersion)
   at LiteDB.Engine.DataService.<Read>d__5.MoveNext()
   at LiteDB.Engine.BufferReader.MoveForward(Int32 count)
   at LiteDB.Engine.BufferReader.Read(Byte[] buffer, Int32 offset, Int32 count)
   at LiteDB.Engine.BufferReader.ReadString(Int32 count)
   at LiteDB.Engine.BufferReader.ReadElement(HashSet`1 remaining, String& name)
   at LiteDB.Engine.BufferReader.ReadDocument(HashSet`1 fields)
   at LiteDB.Engine.BufferReader.ReadElement(HashSet`1 remaining, String& name)
   at LiteDB.Engine.BufferReader.ReadArray()
   at LiteDB.Engine.BufferReader.ReadElement(HashSet`1 remaining, String& name)
   at LiteDB.Engine.BufferReader.ReadDocument(HashSet`1 fields)
   at LiteDB.Engine.BufferReader.ReadElement(HashSet`1 remaining, String& name)
   at LiteDB.Engine.BufferReader.ReadArray()
   at LiteDB.Engine.BufferReader.ReadElement(HashSet`1 remaining, String& name)
   at LiteDB.Engine.BufferReader.ReadDocument(HashSet`1 fields)
   at LiteDB.Engine.DatafileLookup.Load(PageAddress rawId)
   at LiteDB.Engine.DatafileLookup.Load(IndexNode node)
   at LiteDB.Engine.BasePipe.<LoadDocument>d__6.MoveNext()
   at LiteDB.Engine.BasePipe.<Filter>d__8.MoveNext()
   at LiteDB.Engine.QueryPipe.<Select>d__2.MoveNext()
   at LiteDB.Engine.QueryExecutor.<>c__DisplayClass10_0.<<ExecuteQuery>g__RunQuery|0>d.MoveNext()
   at LiteDB.BsonDataReader.Read()
   at LiteDB.SharedDataReader.Read()
   at LiteDB.LiteQueryable`1.<ToDocuments>d__26.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ABC.Server.GetTasksCollection()

When this is happening, the server has 1570 MB RAM available
The process itself has these stats:
WorkingSet (MB): 667.7734375
PrivateMemorySize (MB): 588.2109375
PeakWorkingSet (MB): 1195.80078125

Everything else (related to DBLite) is still working as expected. GetTasksCollection is only called when a client requests all tasks from the server. Any help would be appreciated.

Kind regards
Martin

**Comment by JKamsker** [comment]
Consolidated into #2813, which combines this report with the related ones and tracks the fix. Closing this as a duplicate — please follow #2813, and comment there if your case is different.
