### ISSUE TITLE
[BUG] Rebuild operation requires no log file

### ISSUE THREAD

**Issue by ghost** [litedb-org/LiteDB#2152]
Litedb 5.0.10, Windows 10, .Net Core 3.1, WPF
Checkpoint set to 0 (manual)

At application start we creating database connection to exist database and perform Checkpoint and after that Rebuild.
Now on some clients I have exception on rebuild operation.

`			var cs = new ConnectionString
			{
				Filename = fileName
			};

			try
			{
				db = new LiteDatabase(cs);

				db.Checkpoint();
				db.Rebuild();
				db.CheckpointSize = 0;
			}
			catch (Exception e)
			{
				Log.Fatal(e, "Database init error");

				throw;
			}`
Expected behavior: successfull rebuild

Stacktrace:
LiteDB.LiteException: Rebuild operation requires no log file - run Checkpoint before continue
   at LiteDB.Engine.LiteEngine.Rebuild(RebuildOptions options)
   at LiteDB.LiteDatabase.Rebuild(RebuildOptions options)

Database log not truncated at all after checkpoint (~35 mb log, 90mb db).

**Comment by BenWoodford** [comment]
Did you ever work out how to fix this, or what causes it? We run Rebuild as well on start to detect some page errors but this has just popped up for the first time ever

**Comment by lzziaini** [comment]
Hello. I have the same question befor , but I found that i do rebuild Success while used LiteDb.Studio. Finally I identified the problem is， I didn't call db.Dispose() manually before closing the program。the log files will auto clear while call "db.Dispose()". And One more thing is you should make sure that dispose func run completed while closing you program.（I call dispose in destructor，but my program exit faster ，so dispose was not completed and log file still exist）
 Hope can help you. Good Luck.

**Comment by JKamsker** [comment]
This is fixed on the `dev` branch. `dev` ships as the LiteDB 6.x prereleases.

Please try the latest prerelease (currently **6.0.0-prerelease.81**):

```
dotnet add package LiteDB --prerelease
```

If the problem still happens on the prerelease, comment here with the version you used and a repro, and we'll reopen the issue.
