### ISSUE TITLE
[BUG] Migration from 4.1.4  to 5.0.11 - Cannot insert duplicate key in unique index

### ISSUE THREAD

**Issue by DamianResler** [litedb-org/LiteDB#2159]
**Version**
LiteDB 5.0.11
Win10
.net 4.6.2

_id type is  LiteDB.ObjectId

update db from 4.1.4 ends with error:
LiteDB.LiteException: Cannot insert duplicate key in unique index '_id'. The duplicate value is '{"$oid":"61702cdfcac9120b580ba36a"}'.
   w LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte level, IndexNode last)
   w LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, IndexNode last)
   w LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   w LiteDB.Engine.LiteEngine.RebuildContent(IFileReader reader)
   w LiteDB.Engine.LiteEngine.Upgrade(String filename, String password, Collation collation)
   w LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)

**Comment by petertiedemann** [comment]
I have the same problem in 5.0.20:
```
LiteDB.LiteException: Cannot insert duplicate key in unique index '_id'. The duplicate value is '"59803E0EF693557459A7BCA047C118F998256C06E4BF7A1C4880012FF97E47B2"'.
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte insertLevels, IndexNode last)
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, IndexNode last)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.RebuildContent(IFileReader reader)
   at LiteDB.Engine.RebuildService.Rebuild(RebuildOptions options)
   at LiteDB.Engine.LiteEngine.Recovery(Collation collation)
   at LiteDB.Engine.LiteEngine.TryUpgrade()
   at LiteDB.Engine.LiteEngine.Open()
   at LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
   at LiteDB.ConnectionString.CreateEngine()
   at LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)
   at LiteDB.LiteDatabase..ctor(String connectionString, BsonMapper mapper)
```

**Comment by JKamsker** [comment]
@petertiedemann Could you please provide a repro?`

**Comment by petertiedemann** [comment]
> @petertiedemann Could you please provide a repro?
> 
> also #2366

I found #2366 first, and then realized this older issue described the same issue. I will try and investigate how sensitive the data in this file is, to see if i can actually share it.

**Comment by JKamsker** [comment]
Without repro, we can not even attempt to fix it. 
So either try creating one or fix it yourself and create a pr then :)

**Comment by petertiedemann** [comment]
@JKamsker Sure, I know how tricky debugging without a repro is :) But I think I was actually tricked by this one: https://github.com/mbdavid/LiteDB/issues/2434 . Eg. the file I was trying to upgrade was previously attempted opened *without* upgrade specified, and ended up corrupting the file. So, my conclusion is that the upgrade actually works, but if I open the file first without upgrade, it gets corrupted. As there is already a repro for that bug, I guess no further action is needed.

**Comment by JKamsker** [comment]
Consolidated into #2823, which combines this report with the related ones and tracks the fix. Closing this as a duplicate — please follow #2823, and comment there if your case is different.
