### ISSUE TITLE
[BUG] Error in parallel Insert (Also Upsert)

### ISSUE THREAD

**Issue by hilevelhdd** [litedb-org/LiteDB#2169]
**Version**
Which LiteDB version/OS/.NET framework version are you using. 5.0.11

**Describe the bug**
/**************/
Unhandled exception. System.Exception: LiteDB ENSURE: transaction must be active to rollback (current state: Disposed)
   at LiteDB.Constants.ENSURE(Boolean conditional, String message)
   at LiteDB.Engine.TransactionService.Rollback()
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at ALPRDesigned.Classes.IO.PlateSaveToLocation(CameraDetection _EE, Native native) in C:\Users\Rahmati-PC\source\repos\ALPRDesigned\Classes\IO.cs:line 72
   at ALPRDesigned.Classes.Camera_PlateDetector.OnPlateDetectedForHighway(Native native, PlateResult result) in C:\Users\Rahmati-PC\source\repos\ALPRDesigned\Classes\Camera_PlateDetector\ForHighWay.cs:line 94
   at ALPRDesigned.Classes.Camera_PlateDetector.<>c__DisplayClass13_0.<PlateFeatureExtract>b__0() in C:\Users\Rahmati-PC\source\repos\ALPRDesigned\Classes\Camera_PlateDetector\Main.cs:line 119
/*************/

**Code to Reproduce**
Write a small snippet to isolate your bug and could be possible to our team test. 
in MultiThread insert, The above error occurs.
* Approximately 10 to 20 storage per second. The size of each storage is 500 bytes

**Screenshots/Stacktrace**
![123](https://user-images.githubusercontent.com/14278404/162192629-34cd2152-591c-41b7-b43a-bbf6a29be614.jpg)

**Comment by ArsenijK** [comment]
This happens very often. And the problem is it hides original Exception. Because it's in the catch clause, that Rollback() is called and without a new try/catch, so original Exception is lost forever and instead you get this RollBack in Diposed state Exception. I don't know which is more important one, original, or RollBack or maybe both with something like AggregateException? And maybe in catch clause one should check if it already Disposed and impossible to Rollback?

**Comment by Blue101black** [comment]
@hilevelhdd Did you ever figure out this issue, or create a unit test that could reproduce it reliably?

**Comment by JKamsker** [comment]
This doesn't reproduce on current `dev`, so closing.

42eae45b0 (#2848) now rolls back an auto-transaction only while it is still `Active`. The "rollback in Disposed state" ENSURE can no longer replace the original exception, so if something else fails you now get the real error.

Verified on `dev` @ faad53821: 16 threads running `Insert` and `Upsert` across 3 collections for 5 s, 0 errors. The original trigger in this report is unknown. If you still get an exception on a current prerelease, please reopen with its message and stack trace.
