### ISSUE TITLE
[BUG]  Long Field Names (>200 characters) causing collection corruption

### ISSUE THREAD

**Issue by dgodwin1175** [litedb-org/LiteDB#2183]
**Version**
4.1.4

**Describe the bug**
When creating a new DateTime field in a document, if I enter a FieldName whose length is 255 characters, the collection is corrupted.
Any time I try to load the collection after that I get the following exception:
2022-05-13 14:24:47.663 [21] ERROR ChCcLogger::LogError(35)	Caught exception: Value to add was out of range.
Parameter name: value
2022-05-13 14:24:47.670 [21] DEBUG ChCcLogger::LogError(35)	Stack trace following:
   at System.DateTime.Add(Double value, Int32 scale)
   at LiteDB.BsonReader.ReadElement(ByteReader reader, String& name)
   at LiteDB.BsonReader.ReadDocument(ByteReader reader)
   at LiteDB.BsonReader.ReadElement(ByteReader reader, String& name)
   at LiteDB.BsonReader.ReadDocument(ByteReader reader)
   at LiteDB.QueryCursor.Fetch(TransactionService trans, DataService data, BsonReader bsonReader)
   at LiteDB.LiteEngine.<Find>d__9.MoveNext()
   at LiteDB.LiteEngine.<Find>d__13.MoveNext()
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)

**Code to Reproduce**
I can reproduce this using GUI tools like LiteDbExplorer

**Expected behavior**
Need to know if there's a limit to FieldName length, or whether this is a defect.  If there is a limit, LiteDb should reject the entry and prevent the corruption.

**Comment by JKamsker** [comment]
This is fixed on the `dev` branch. `dev` ships as the LiteDB 6.x prereleases.

Please try the latest prerelease (currently **6.0.0-prerelease.81**):

```
dotnet add package LiteDB --prerelease
```

If the problem still happens on the prerelease, comment here with the version you used and a repro, and we'll reopen the issue.
