### ISSUE TITLE
[BUG] Value was too small or to large int64 when using BsonExpression

### ISSUE THREAD

**Issue by kszwaj-catalogicsoftware** [litedb-org/LiteDB#2205]
**Version**
5.0.9 5.0.12

**Describe the bug**
collection.Find(BsonExpression) is thrown exception.

When in BsonExpression put the value higher than max limit of Int64 or Int32. F.e 111111111111111111111111111111111111 it should be parsed as String, because the field which I try to find is String type.
BsonExpression: `"$.Name = 1111111111111111111111111"`

**Code to Reproduce**
`results = col.Find($"$.{filters.First().var} {filters.First().op} \'{filters.First().val}\'").ToList();`

**Expected behavior**

**Screenshots/Stacktrace**
``System.OverflowException: Value was either too large or too small for an Int64.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt64(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at LiteDB.BsonExpressionParser.TryParseInt(Tokenizer tokenizer, BsonDocument parameters)
   at LiteDB.BsonExpressionParser.ParseSingleExpression(Tokenizer tokenizer, ExpressionContext context, BsonDocument parameters, DocumentScope scope)
   at LiteDB.BsonExpressionParser.ParseFullExpression(Tokenizer tokenizer, ExpressionContext context, BsonDocument parameters, DocumentScope scope)
   at LiteDB.BsonExpression.ParseAndCompile(Tokenizer tokenizer, BsonExpressionParserMode mode, BsonDocument parameters, DocumentScope scope)``

**Additional context**

**Comment by JKamsker** [comment]
The `OverflowException` is fixed on `dev` (#2916): an integer literal beyond Int64 now parses as a number (`Decimal`, or `Double` when even larger). That does **not** yet do what you asked for — an unquoted digit-only value still does not match a *string* field, exactly like `$.Name = 123` never matched `"123"`. That part is tracked in #2929. Until then, quote the value or, better, pass it as a parameter so it keeps its type: `col.Find(BsonExpression.Create("$.Name = @0", new BsonValue(value)))`.
