### ISSUE TITLE
[BUG] Right parameter must be a scalar expression in function.

### ISSUE THREAD

**Issue by g1ga** [litedb-org/LiteDB#2238]
**Version**
LIteDb 5.0.9.0 / Windows / DotNet 6

**Bug description**
potentially BsonExpression wrong parsing when using "Or"

**Code to Reproduce**
var collection = GetCollection(db);
var qry = collection.Query();
  var exprList = new List<BsonExpression>
  {
             Query.Contains("RootList[\*].Id ANY", "blablah"),
             Query.Contains("RootList[\*].Names[\*] ANY",  "blablah"),
  };
  var orExpression = Query.Or(exprList.ToArray());
  qry = qry.Where(orExpression);

**Expected behavior**
To work fine, syntax tested ok, single query works fine.
this query works fine:
SELECT $ FROM collection 
    where 
        $.RootList[\*].PlatformId ANY like '%blah%' OR
        $.RootList[\*].Names[\*] ANY like '%blah%'

**Screenshots/Stacktrace**
```
 LiteDB.LiteException: Right parameter must be a scalar expression in function.
         at LiteDB.BsonExpressionParser.ParseFunction(String functionName, BsonExpressionType type, Tokenizer tokenizer, ExpressionContext context, BsonDocument parameters, DocumentScope scope)
         at LiteDB.BsonExpressionParser.TryParseFunction(Tokenizer tokenizer, ExpressionContext context, BsonDocument parameters, DocumentScope scope)
         at LiteDB.BsonExpressionParser.ParseSingleExpression(Tokenizer tokenizer, ExpressionContext context, BsonDocument parameters, DocumentScope scope)
         at LiteDB.BsonExpressionParser.ParseFullExpression(Tokenizer tokenizer, ExpressionContext context, BsonDocument parameters, DocumentScope scope)
         at LiteDB.BsonExpressionParser.TryParseInnerExpression(Tokenizer tokenizer, ExpressionContext context, BsonDocument parameters, DocumentScope scope)
         at LiteDB.BsonExpressionParser.ParseSingleExpression(Tokenizer tokenizer, ExpressionContext context, BsonDocument parameters, DocumentScope scope)
         at LiteDB.BsonExpressionParser.ParseFullExpression(Tokenizer tokenizer, ExpressionContext context, BsonDocument parameters, DocumentScope scope)
         at LiteDB.BsonExpression.ParseAndCompile(Tokenizer tokenizer, BsonExpressionParserMode mode, BsonDocument parameters, DocumentScope scope)
         at LiteDB.BsonExpression.Create(Tokenizer tokenizer, BsonExpressionParserMode mode, BsonDocument parameters)
         at LiteDB.BsonExpression.Create(String expression, BsonDocument parameters)
         at LiteDB.BsonExpression.Create(String expression)
         at LiteDB.BsonExpression.op_Implicit(String expr)
         at LiteDB.Query.Or(BsonExpression left, BsonExpression right)
         at LiteDB.Query.Or(BsonExpression[] queries)
```

**Comment by pjy612** [comment]
it work in 5.0.12 ?
![image](https://user-images.githubusercontent.com/4072526/190962464-8d05343b-9e47-4915-97d9-1dda2863949b.png)

**Comment by JKamsker** [comment]
This is fixed on the `dev` branch. `dev` ships as the LiteDB 6.x prereleases.

Please try the latest prerelease (currently **6.0.0-prerelease.81**):

```
dotnet add package LiteDB --prerelease
```

If the problem still happens on the prerelease, comment here with the version you used and a repro, and we'll reopen the issue.
