### ISSUE TITLE
[QUESTION] System.Exception: LiteDB ENSURE: pages in memory store must be non-shared

### ISSUE THREAD

**Issue by UlyssesWu** [litedb-org/LiteDB#2252]
```
Unhandled exception. System.Exception: LiteDB ENSURE: pages in memory store must be non-shared
   at LiteDB.Constants.ENSURE(Boolean conditional, String message)
   at LiteDB.Engine.MemoryCache.GetFreePage()
   at LiteDB.Engine.MemoryCache.<>c__DisplayClass5_0.<GetReadablePage>b__0(Int64 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at LiteDB.Engine.MemoryCache.GetReadablePage(Int64 position, FileOrigin origin, Action`2 factory)
   at LiteDB.Engine.Snapshot.ReadPage[T](UInt32 pageID, FileOrigin& origin, Int64& position, Int32& walVersion)
   at LiteDB.Engine.Snapshot.GetPage[T](UInt32 pageID, FileOrigin& origin, Int64& position, Int32& walVersion)
   at LiteDB.Engine.IndexEquals.Execute(IndexService indexer, CollectionIndex index)+MoveNext()
   at LiteDB.LinqExtensions.<>c__DisplayClass2_0`2.<<DistinctBy>g___|0>d.MoveNext()
   at LiteDB.Engine.BasePipe.LoadDocument(IEnumerable`1 nodes)+MoveNext()
   at LiteDB.Engine.BasePipe.Filter(IEnumerable`1 source, BsonExpression expr)+MoveNext()
   at LiteDB.Engine.BasePipe.Filter(IEnumerable`1 source, BsonExpression expr)+MoveNext()
   at LiteDB.Engine.QueryPipe.Select(IEnumerable`1 source, BsonExpression select)+MoveNext()
   at LiteDB.Engine.QueryExecutor.<>c__DisplayClass10_0.<<ExecuteQuery>g__RunQuery|0>d.MoveNext()
   at LiteDB.Engine.QueryExecutor.ExecuteQuery(Boolean executionPlan)
   at LiteDB.Engine.LiteEngine.Query(String collection, Query query)
   at LiteDB.LiteQueryable`1.ToDocuments()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at MyAspNetWebsite.MyClass.MyMethod()
```

This happens randomly (the program has been running for 1 day without error). Why?

I'm using [litedb-async](https://github.com/mlockett42/litedb-async) (idk if this is the reason) and the exception throwed in this line:

~~`await myLiteDB.GetCollection<Run>().UpsertAsync(run);`~~

(Should be this line:)
`var records = (await myLiteDB.GetCollection<Record>().FindAsync(r => r.A == 0 && r.B == b && r.Time >= beginTime).ToList());`

**Comment by ProKn1fe** [comment]
Really interesting bug because i don't know how even try to reproduce it xd. Feels like some kind of trying access from multiple threads, but there is a ConcurrentQueue, so i don't know how to reproduce this.

https://github.com/mbdavid/LiteDB/blob/6d9ac6237ff8cae104a3c57a8de4ec55b4506e87/LiteDB/Engine/Disk/MemoryCache.cs#L270

```C#
if (_free.TryDequeue(out var page))
{
    ENSURE(page.Position == long.MaxValue, "pages in memory store must have no position defined");
    ENSURE(page.ShareCounter == 0, "pages in memory store must be non-shared");

    return page;
}
```
How this page returns back:
```C#
public void DiscardPage(PageBuffer page)
{
    ENSURE(page.ShareCounter == BUFFER_WRITABLE, "discarded page must be writable");

    // clear page controls
    page.ShareCounter = 0;
    page.Position = long.MaxValue;

    // DO NOT CLEAR CONTENT
    // when this page will requested from free list will be clear if request was from NewPage()
    //  or will be overwrite by ReadPage

    // added into free list
    _free.Enqueue(page);
}
```

**Comment by JKamsker** [comment]
Consolidated into #2817, which combines this report with the related ones and tracks the fix. Closing this as a duplicate — please follow #2817, and comment there if your case is different.
