### ISSUE TITLE
[BUG] ENSURE: pages in memory store must be non-shared

### ISSUE THREAD

**Issue by FedeC87p** [litedb-org/LiteDB#2282]
**Version**
<PackageReference Include="LiteDB" Version="5.0.15" />
<TargetFramework>net7.0</TargetFramework>
<Project Sdk="Microsoft.NET.Sdk"> Application Console

**Describe the bug**
Only one time after intensive use of read/write of data

**Code to Reproduce**
`var collection = db.GetCollection<RevealContainerEntity>("tbl_revealpool");
            collection.EnsureIndex("BlockNumberIsProcessed", x => new { x.BlockNumber, x.IsProcessed });

            return collection.Find(x => !x.IsProcessed)
                .Select(i => i.BlockNumber)
                .Distinct()
                .ToList();`

**Screenshots/Stacktrace**
System.Exception: LiteDB ENSURE: pages in memory store must be non-shared
   at LiteDB.Constants.ENSURE(Boolean conditional, String message)
   at LiteDB.Engine.MemoryCache.GetFreePage()
   at LiteDB.Engine.MemoryCache.<>c__DisplayClass5_0.<GetReadablePage>b__0(Int64 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at LiteDB.Engine.MemoryCache.GetReadablePage(Int64 position, FileOrigin origin, Action`2 factory)
   at LiteDB.Engine.Snapshot.ReadPage[T](UInt32 pageID, FileOrigin& origin, Int64& position, Int32& walVersion)
   at LiteDB.Engine.Snapshot.GetPage[T](UInt32 pageID, FileOrigin& origin, Int64& position, Int32& walVersion)
   at LiteDB.Engine.DataService.Read(PageAddress address)+MoveNext()
   at LiteDB.Engine.BufferReader..ctor(IEnumerable`1 source, Boolean utcDate)
   at LiteDB.Engine.DatafileLookup.Load(PageAddress rawId)
   at LiteDB.Engine.BasePipe.LoadDocument(IEnumerable`1 nodes)+MoveNext()
   at LiteDB.Engine.BasePipe.Filter(IEnumerable`1 source, BsonExpression expr)+MoveNext()
   at LiteDB.Engine.QueryPipe.Select(IEnumerable`1 source, BsonExpression select)+MoveNext()
   at LiteDB.Engine.QueryExecutor.<>c__DisplayClass10_0.<<ExecuteQuery>g__RunQuery|0>d.MoveNext()
   at LiteDB.BsonDataReader.Read()
   at LiteDB.LiteQueryable`1.ToDocuments()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.DistinctIterator`1.ToList()
   at LiteDB.DbContext.RevealPoolDbContext.GetBlockWithRevealInProcess()

**Comment by JKamsker** [comment]
Consolidated into #2817, which combines this report with the related ones and tracks the fix. Closing this as a duplicate — please follow #2817, and comment there if your case is different.
