### ISSUE TITLE
[BUG] System.Reflection.AmbiguousMatchException: Ambiguous match found

### ISSUE THREAD

**Issue by okarpov** [litedb-org/LiteDB#2308]
**Version**
5.0.16

**Describe the bug**
Using this version and 5.0.15 leads to System.Reflection.AmbiguousMatchException: Ambiguous match found 
after some time of usage

**Code to Reproduce**
its simple - just make a simple multithread code to generate and insert/update typed objects inside of a collection
we use the following class:
```
public class Cookie
    {
        public long Id { get; set; }
        public string Guid { get; set; }
        public long Long { get; set; }
        public CookieCollection cookieCollection { get; set; }
    }
```

**Expected behavior**
should not be any issue

**Screenshots/Stacktrace**
   at System.RuntimeType.GetMethodImplCommon(String name, Int32 genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at LiteDB.BsonMapper.DeserializeList(Type type, BsonArray value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.DeserializeObject(EntityMapper entity, Object obj, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.LiteQueryable`1.<ToEnumerable>b__27_2(BsonDocument x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at LiteDB.LiteCollection`1.FindById(BsonValue id)

**Additional context**

**Comment by okarpov** [comment]
removing ```public CookieCollection cookieCollection { get; set; }``` property seems solving the issue
but then there is another issue - can not add same _id value

**Comment by Luigi6821** [comment]
Hi, I found same issue when deserializing collection.
The bug is in line 260 of file BsonMapper.Deserialize.cs.
The affected line is the following:
var addMethod = type.GetMethod("Add");
Which could cause problem when type contains more than one Add method but deserialize need only the one having
as argument itemType.
So if you do the following:
var addMethod = type.GetMethod("Add", new Type[] { itemType });
it solves the issue.

Please let me know if a bug fix can be released soon.
Thanks in advance.

Regards
Luigi

**Comment by mbdavid** [comment]
Thanks for your PR @Luigi6821!! I will review to add some tests about this.

**Comment by JKamsker** [comment]
This is fixed on the `dev` branch. `dev` ships as the LiteDB 6.x prereleases.

Please try the latest prerelease (currently **6.0.0-prerelease.81**):

```
dotnet add package LiteDB --prerelease
```

If the problem still happens on the prerelease, comment here with the version you used and a repro, and we'll reopen the issue.
