### ISSUE TITLE
[BUG] Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks

### ISSUE THREAD

**Issue by Cruik** [litedb-org/LiteDB#2318]
**Version**
LiteDB 5.0.16 / .Net6 Maui-Android

**Describe the bug**

When i try to get some collection of my db i get the following exception:

`Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks. (Parameter 'ticks')`

**Code to Reproduce**
```
using var db = new LiteDatabase(await GetConnectionString());

var colConfig = db.GetCollection<ConfigurationEntity>("config");
```

**Expected behavior**
Do not throw an exception and return the saved data

**Screenshots/Stacktrace**

> (LobiLocalLiteDatabase)Error: System.ArgumentOutOfRangeException: Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks. (Parameter 'ticks')
   at System.DateTime.ThrowTicksOutOfRange()
   at System.DateTime..ctor(Int64 ticks, DateTimeKind kind)
   at LiteDB.BufferSliceExtensions.ReadDateTime(BufferSlice buffer, Int32 offset)
   at LiteDB.Engine.HeaderPage..ctor(PageBuffer buffer)
   at LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
   at LiteDB.ConnectionString.CreateEngine()
   at LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)
   at LiteDB.LiteDatabase..ctor(String connectionString, BsonMapper mapper)
   at Lobi.Local.Storage.LobiLocalLiteDatabase.LoadConfiguration() in D:\work\awagd\LOBI\New\src\Lobi.Local.Storage\LobiLocalLiteDatabase.cs:line 278 - Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks. (Parameter 'ticks') 
     at System.DateTime.ThrowTicksOutOfRange()
   at System.DateTime..ctor(Int64 ticks, DateTimeKind kind)
   at LiteDB.BufferSliceExtensions.ReadDateTime(BufferSlice buffer, Int32 offset)
   at LiteDB.Engine.HeaderPage..ctor(PageBuffer buffer)
   at LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
   at LiteDB.ConnectionString.CreateEngine()
   at LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)
   at LiteDB.LiteDatabase..ctor(String connectionString, BsonMapper mapper)
   at Lobi.Local.Storage.LobiLocalLiteDatabase.LoadConfiguration() in D:\work\awagd\LOBI\New\src\Lobi.Local.Storage\LobiLocalLiteDatabase.cs:line 278

**Additional context**
my db file is protected with an password. But the password only contains letters and numbers
My LiteDb does not contain any datetime fields in this collections

**Comment by dimplevador** [comment]
@Cruik I faced same problem today. I don't know if you already found the solution or not. Posting it here for anyone else who faces similar issue.

The problem was that the creation date of the db file was corrupted for some reason. After I deleted the corrupted file, it worked fine. No error.

**Comment by JKamsker** [comment]
Consolidated into #2784, which combines this report with the related ones and tracks the fix. Closing this as a duplicate — please follow #2784, and comment there if your case is different.
