### ISSUE TITLE
[BUG] System.Exception: LiteDB ENSURE:

### ISSUE THREAD

**Issue by StrongAndyZhang** [litedb-org/LiteDB#2326]
**Version**
LiteDB version is 5.0.16.

**Describe the bug**
Get an exception when using upload function of filestorage, the exception message is too simple without any detail information.  

2023-05-21 11:56:06,956 System.Exception: LiteDB ENSURE: 
   at LiteDB.Constants.ENSURE(Boolean conditional, String message)
   at LiteDB.LiteFileStream`1..ctor(ILiteCollection`1 files, ILiteCollection`1 chunks, LiteFileInfo`1 file, BsonValue fileId, FileAccess mode)
   at LiteDB.LiteFileInfo`1.OpenWrite()
   at LiteDB.LiteStorage`1.OpenWrite(TFileId id, String filename, BsonDocument metadata)
   at LiteDB.LiteStorage`1.Upload(TFileId id, String filename, Stream stream, BsonDocument metadata)

I found an interesting thing that the chunks count in file collection is not same as the chunks count in chunks collection. Maybe this data cause upload fail. And I don't know how to produce this kind of dirty data.

**Expected behavior**
Upload file successfully.

**Comment by gplogix** [comment]
Same problem (I want to upload a new version of the file). In my problem, it seems the chunk is already deleted as the _chunks are empty.

SELECT $ FROM _files;

{
  "_id": "XXXXXXX.json",
  "filename": "XXXXXXX.json",
  "mimeType": "application/octet-stream",
  "length": {"$numberLong": "4539"},
  "chunks": 1,
  "uploadDate": {"$date": "2023-09-28T13:25:07.3810000Z"},
  "metadata": {}
}

SELECT $ FROM _chunks;
No result

**Comment by Mooreland1999** [comment]
Same problem. Version 5.0.11.

New info:  Same file on two different machines.  One works, one does not.

**Comment by JKamsker** [comment]
Consolidated into #2806, which combines this report with the related ones and tracks the fix. Closing this as a duplicate — please follow #2806, and comment there if your case is different.
