### ISSUE TITLE
[BUG] Non-negative number required. Error when querying the database

### ISSUE THREAD

**Issue by arunprakashn** [litedb-org/LiteDB#2331]
**Version**
Which LiteDB version/OS/.NET framework version are you using. **(REQUIRED)**
5.0.9

**Describe the bug**
Getting the following exception.

Non-negative number required.
Parameter name: count 
System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: count
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at LiteDB.Engine.BufferReader.Read(Byte[] buffer, Int32 offset, Int32 count)
   at LiteDB.Engine.BufferReader.ReadNumber[T](Func`3 convert, Int32 size)
   at LiteDB.Engine.BufferReader.ReadDocument(HashSet`1 fields)
   at LiteDB.Engine.DatafileLookup.Load(PageAddress rawId)
   at LiteDB.Engine.BasePipe.<LoadDocument>d__6.MoveNext()
   at LiteDB.Engine.BasePipe.<Filter>d__8.MoveNext()
   at LiteDB.Engine.QueryPipe.<Select>d__2.MoveNext()
   at LiteDB.Engine.QueryExecutor.<>c__DisplayClass10_0.<<ExecuteQuery>g__RunQuery|0>d.MoveNext()
   at LiteDB.BsonDataReader.Read()
   at LiteDB.LiteQueryable`1.<ToDocuments>d__26.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Platform.IHC.OHS.Data.Repository.BaseRepository`1.Find(Expression`1 predicate, Int32 skip, Int32 limit, Boolean autoSlideEnabled, DataBaseType activeDbMode, DataBaseCategory dataBaseCategory)
   at OHS.Module.Common.Jobs.DataFeedSubscriptionJob.ProcessSubscriptionRequest()
   at OHS.Module.Common.Jobs.DataFeedSubscriptionJob.<Execute>d__5.MoveNext()

**Code to Reproduce**
Write a small snippet to isolate your bug and could be possible to our team test. **(REQUIRED)**

**Expected behavior**

**Screenshots/Stacktrace**
If applicable, add screenshots/stacktrace

**Additional context**

We saw a similar issue https://github.com/mbdavid/LiteDB/issues/1378 but I believe that the fix for this is already in 5.0.9. Hence, this is a new issue albeit the error is the same

**Comment by arunprakashn** [comment]
Any help?

**Comment by arunprakashn** [comment]
Any inputs? We are seeing this more often now.

**Comment by arunprakashn** [comment]
When using the latest library, the exception is a little different
LiteDB ENSURE: get only index below highest index 
System.Exception: LiteDB ENSURE: get only index below highest index
   at LiteDB.Constants.ENSURE(Boolean conditional, String message)
   at LiteDB.Engine.BasePage.Get(Byte index)
   at LiteDB.Engine.DataService.<Read>d__5.MoveNext()
   at LiteDB.Engine.BufferReader..ctor(IEnumerable`1 source, Boolean utcDate)
   at LiteDB.Engine.DatafileLookup.Load(PageAddress rawId)
   at LiteDB.Engine.BasePipe.<LoadDocument>d__6.MoveNext()
   at LiteDB.Engine.BasePipe.<Filter>d__8.MoveNext()
   at LiteDB.Engine.QueryPipe.<Select>d__2.MoveNext()
   at LiteDB.Engine.QueryExecutor.<>c__DisplayClass10_0.<<ExecuteQuery>g__RunQuery|0>d.MoveNext()
   at LiteDB.BsonDataReader..ctor(IEnumerable`1 values, String collection)
   at LiteDB.Engine.QueryExecutor.ExecuteQuery(Boolean executionPlan)
   at LiteDB.Engine.LiteEngine.Query(String collection, Query query)
   at LiteDB.LiteQueryable`1.<ToDocuments>d__26.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)

**Comment by arunprakashn** [comment]
Any updates?

**Comment by JKamsker** [comment]
Consolidated into #2817, which combines this report with the related ones and tracks the fix. Closing this as a duplicate — please follow #2817, and comment there if your case is different.
