### ISSUE TITLE
[BUG] Unhandled exception when trying to open a shared conneciton in .net Framework 4.8

### ISSUE THREAD

**Issue by stigzler** [litedb-org/LiteDB#2393]
**Version**
I am developing on .net Framework 4.8 with LiteDb 5.0.17.0.

**Describe the bug**
When I try to instantiate a database connection with:

```cs
Connection = new LiteDatabase("Filename=C:\\temp\\data.ldb;Connection=Shared");
```

I get the following error:

```txt
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Void System.Threading.Mutex..ctor(Boolean, System.String, Boolean ByRef, System.Security.AccessControl.MutexSecurity)'.
  Source=LiteDB
  StackTrace:
   at LiteDB.SharedEngine..ctor(EngineSettings settings)
   at LiteDB.ConnectionString.CreateEngine()
   at LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)
```

It works fine if I omit the connection specification. I managed to find a few odds and ends for this through google, but couldn't match to my particular use case. However, it looks like something to do with .net versions and Mutex (which I'm not familiar with)??

I did find this in your docs:

"The Shared mode only works in .NET implementations that provide named mutexes. Its multi-process capabilities will only work in platforms that implement named mutexes as system-wide mutexes."

However, I have no idea what this means, whether this applies to Framework 4.8 or not and indeed what to do as a result.

Any suggestions?

**Code to Reproduce**
```cs
Connection = new LiteDatabase("Filename=C:\\temp\\data.ldb;Connection=Shared");
```

**Expected behavior**
Shared Connection is opened

**Comment by fil-at-werma** [comment]
I've opened a Bounty of 50 rep for an exhaustive answer to this on Stackoverflow: https://stackoverflow.com/questions/77539735/litedb-throws-unhandled-exception-when-trying-to-open-a-shared-connection

expiring in 7 days.

**Comment by JKamsker** [comment]
This is the same problem as #2079, which is fixed on the `dev` branch. `dev` ships as the LiteDB 6.x prereleases.

Please try the latest prerelease (currently **6.0.0-prerelease.81**):

```
dotnet add package LiteDB --prerelease
```

If the problem still happens on the prerelease, comment here with the version you used and a repro, and we'll reopen the issue.
