### ISSUE TITLE
[BUG] Tests about `DAY()` fails in Japan Standard Time

### ISSUE THREAD

**Issue by anatawa12** [litedb-org/LiteDB#2414]
**Version**
Which LiteDB version/OS/.NET framework version are you using. **(REQUIRED)**
- litedb aff0bd844d032b13dfff4c4e2c0ac18e674b13d9
- macOS 14.2.1 23C71 arm64 
- .NET 8.0.100

**Describe the bug**

`DAY` `MONTH` `YEAR` is timezone dependent so this test fails in JST

https://github.com/mbdavid/LiteDB/blob/aff0bd844d032b13dfff4c4e2c0ac18e674b13d9/LiteDB.Tests/Expressions/Expressions_Exec_Tests.cs#L215

**Steps to Reproduce**

1. configure your pc to Japan Standard Time
2. `dotnet test`

**Expected behavior**
No test failure

**Screenshots/Stacktrace**
If applicable, add screenshots/stacktrace

```
[xUnit.net 00:00:01.26]     LiteDB.Tests.Expressions.ExpressionsExec_Tests.Expressions_Scalar_Methods [FAIL]
  Failed LiteDB.Tests.Expressions.ExpressionsExec_Tests.Expressions_Scalar_Methods [244 ms]
  Error Message:
   Expected value to be equal to 1, but found 2.
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.ComparableTypeAssertions`1.Be(T expected, String because, Object[] becauseArgs)
   at LiteDB.Tests.AssertEx.ExpectValue(BsonValue value, BsonValue expect) in /Users/anatawa12/RiderProjects/LiteDB/LiteDB.Tests/Utils/AssertEx.cs:line 40
   at LiteDB.Tests.Expressions.ExpressionsExec_Tests.Expressions_Scalar_Methods() in /Users/anatawa12/RiderProjects/LiteDB/LiteDB.Tests/Expressions/Expressions_Exec_Tests.cs:line 215
```

**Additional context**

I don't know if `DAY` `YEAR` and `MONTH` are expected to be timezone dependant or not but I think some applications depend on timezone dependant behavior so I assume this is bug of test, not of application

**Comment by pgrimstrup** [comment]
This issue should be bumped as it is appears to be a fundamental mishandling of date/times.

The Expressions_Scalar_Methods unit test checks the ``DAY``, ``MONTH`` and ``YEAR`` functions. These functions appear to be returning results that are based on Local Time Zone. The date value being supplied is UTC. As a result, the tests pass in their current state if your Local Time Zone is +04:00 or lower (eg, USA). The tests fail when Local Time Zone is over +04:00 (eg, Japan, New Zealand) 

Note that the ``YEAR/MONTH/DAY`` tests do not (but should) include ``HOUR``, as this would result in a failing test across all Time Zones other than +00:00 (UTC/GMT)

Reproduction:
Change the test value to ``2018-12-31T23:59:59Z``. Change Local Time Zone to anywhere from +01:00 to +12:00.
``DAY`` returns 1
``MONTH`` returns 1
``YEAR`` returns 2019
``HOUR`` returns 12 = 23 plus Local Time Zone Offset as at 2018-12-31, which for me is NZDT +13:00 (=23+13 mod 24)

Change the test value to ``2019-01-01T00:00:01Z``. Change Local Time Zone to anywhere from -12:00 to -01:00.
``DAY`` returns 31
``MONTH`` returns 12
``YEAR`` returns 2018 
``HOUR`` returns 19 = 0 plus Local Time Zone Offset as at 2019-01-01, for USA EST -05:00, (=0-5 mod 24)

Effectively, ``DAY``, ``MONTH``, ``YEAR`` suffer from boundary condition errors and ``HOUR`` is only correct, at most, half the time.

If this is in fact the intended behavior (apparently Date/Times are converted to UTC when stored and converted to Local TZ when retrieved), then Date/Time SQL functions will require some way to denote the desired Time Zone when it is retrieved from the DB.

**Comment by JKamsker** [comment]
Thanks for digging into this — I agree this points at a broader DateTime semantics problem rather than just a timezone-sensitive test.

For v6, I think we should make DateTime behavior deterministic: persist and operate on timestamps as UTC, return UTC by default, and only convert to local time explicitly (for example via `TO_LOCAL(...)`). That would also keep `YEAR()`, `MONTH()`, `DAY()` and `HOUR()` from silently changing based on the machine's local timezone.

I've opened #2982 to track the broader v6 DateTime/UTC semantics separately, including `DateTimeKind` handling, `UtcDate`, `DateTimeOffset`, mapper behavior, query semantics, and timezone/DST coverage.

Thanks again for the detailed examples — the boundary cases make the problem especially clear.
