### ISSUE TITLE
[BUG] System.InvalidOperationException: Collection was modified; enumeration operation may not execute. on multi thread inserts

### ISSUE THREAD

**Issue by megedsh** [litedb-org/LiteDB#2565]
**Version**
LiteDB 5.0.21 / .NET 472

**Describe the bug**
InvalidOperationException Collection was modified when inserting from multiple threads
Bug could already be solved by [2536](https://github.com/mbdavid/LiteDB/pull/2538)

**Code to Reproduce**
Sorry - the code is on a machine with no internet access
to reproduce do multiple serializations of the same type, from multiple threads using the same BsonMapper instance

Thread A enters GetEntityMapper and does not find the mapper.
Thread A calls BuildAddEntityMapper, and goes past, adding an entity mapper to the _entities dictionary but not yet updating the List<MemberMapper> Members  of the mapper

thread B enters GetEntityMapper. 
Thread B finds a mapper and returns, but this mapper is still being populated by thread A
Thread B Iterates over the List<MemberMapper> Members - while thread A adds to the same list

Thread B throws the exception below

**Screenshots/Stacktrace**

**System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
    at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
    at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
    at LiteDB.BsonMapper.SerializeObject(Type type, Object obj, Int32 depth)
    at LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)
    at LiteDB.BsonMapper.ToDocument(Type type, Object entity)
    at LiteDB.BsonMapper.ToDocument[T](T entity)
    at LiteDB.LiteCollection`1.<GetBsonDocs>d__52.MoveNext()
    at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction)
    at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)**

**Additional context**
this issue was probably introduced by this fix : [2493](https://github.com/mbdavid/LiteDB/pull/2493)
so it might be short lived - I did not see any other similar issues reported - but you guys probably know better.

I am still waiting for the release of the fix [2536](https://github.com/mbdavid/LiteDB/pull/2538) to validate if it is fixed this current issue.

**Comment by JKamsker** [comment]
This is the same problem as #2732, which is fixed on the `dev` branch. `dev` ships as the LiteDB 6.x prereleases.

Please try the latest prerelease (currently **6.0.0-prerelease.81**):

```
dotnet add package LiteDB --prerelease
```

If the problem still happens on the prerelease, comment here with the version you used and a repro, and we'll reopen the issue.
