### ISSUE TITLE
[BUG] DIspose() won't dispose sometimes. Throws exception

### ISSUE THREAD

**Issue by arunprakashn** [litedb-org/LiteDB#2574]
**Version**
5.0.21

**Describe the bug**
Does not DIspose properly sometimes. 

**Code to Reproduce**
Unable to provide. This is a high throughput read/write but protected with "lock" statements

**Expected behavior**
Should Dispose properly

System.Exception: LiteDB ENSURE: discarded page must be writable
   at LiteDB.Constants.ENSURE(Boolean conditional, String message)
   at LiteDB.Engine.MemoryCache.DiscardPage(PageBuffer page)
   at LiteDB.Engine.DiskService.DiscardDirtyPages(IEnumerable`1 pages)
   at LiteDB.Engine.TransactionService.Dispose(Boolean dispose)
   at LiteDB.Engine.TransactionMonitor.Dispose()
   at LiteDB.Engine.LiteEngine.Dispose(Boolean disposing)
   at LiteDB.Engine.LiteEngine.Dispose()
   at LiteDB.LiteDatabase.Dispose(Boolean disposing)
   at LiteDB.LiteDatabase.Dispose()

**Comment by dos-ise** [comment]
this looks like it is the same issue as this.

https://github.com/litedb-org/LiteDB/issues/2528

**Comment by JKamsker** [comment]
This is the same problem as #2288, which is fixed on the `dev` branch. `dev` ships as the LiteDB 6.x prereleases.

Please try the latest prerelease (currently **6.0.0-prerelease.81**):

```
dotnet add package LiteDB --prerelease
```

If the problem still happens on the prerelease, comment here with the version you used and a repro, and we'll reopen the issue.
