### ISSUE TITLE
Unable to write to a DB file on a macOS

### ISSUE THREAD

**Issue by DeeGeeMan** [litedb-org/LiteDB#787]
I've tried using both LiteRepository and LiteDatabase to create and open a new DB, but I am getting an error when calling Insert.

**Error:**
Exception has occurred: CLR/System.PlatformNotSupportedException
An unhandled exception of type 'System.PlatformNotSupportedException' occurred in LiteDB.dll: 'Locking/unlocking file regions is not supported on this platform. Use FileShare on the entire file instead.'
   at System.IO.FileStream.LockInternal(Int64 position, Int64 length)
   at LiteDB.FileHelper.TryExec(Action action, TimeSpan timeout)
   at LiteDB.StreamExtensions.TryLock(FileStream stream, Int64 position, Int64 length, TimeSpan timeout)
   at LiteDB.FileDiskService.Lock(LockState state, TimeSpan timeout)
   at LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log)
   at LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
   at LiteDB.LazyLoad`1.get_Value()
   at LiteDB.LiteCollection`1.Insert(T document)
   at LiteDbDemo.Program.Main(String[] args) in /Users/grantd/Projects/Ecs/LiteDbDemo/Program.cs:line 20

**Comment by mbdavid** [comment]
Hi @Devin-Grant, I didn´t know about this macOS limitation (lock/unlock regions). In this case, try use `mode=Exclusive` in your [connection string](https://github.com/mbdavid/LiteDB/wiki/Connection-String).

**Comment by Devin-Grant** [comment]
Thant works!

**Comment by avfranco-br** [comment]
Hi guys, I had the same issue above, used the Mode=Exclusive, however when trying to insert a new document (Employees.Insert(Employee)) getting the error - System.ArgumentNullException: Value cannot be null.
Parameter name: filename
   at LiteDB.FileDiskService..ctor(String filename, FileOptions options)
   at LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
   at LiteDB.LazyLoad`1.get_Value()
   at LiteDB.LiteCollection`1.Insert(T document)
   at LiteDBSample.Program.Main(String[] args) in

Any thoughts? Many thanks, Alexandre

**Comment by lazlo-bonin** [comment]
I get the same issue as above.

**Comment by JKamsker** [comment]
This is fixed on the `dev` branch. `dev` ships as the LiteDB 6.x prereleases.

Please try the latest prerelease (currently **6.0.0-prerelease.81**):

```
dotnet add package LiteDB --prerelease
```

If the problem still happens on the prerelease, comment here with the version you used and a repro, and we'll reopen the issue.
